surge-synthesizer/surge-rack

Makefile
README.md
patches/SurgeFX.vcv
src/SurgeFX.cpp
src/SurgeFX.hpp
src/SurgeRackGUI.hpp

This shows the delay working in an ultra-alpha version

Delay working, ultra-alpha

---

res/vectors/SurgeVCV.js
res/vectors/index.html

These are drawn with javascript and canvas. Its all just an initial pass. I was hoping we could interchange files this way to help streamline the development of the GUI but I realize that this stuff may not be that portable.
I hope its clean enough to get the knobs going.

Upload of intitial pass at GUI assets

---

Makefile
README.md
azure-pipelines.yml
src/SurgeFX.cpp
src/SurgeFX.hpp
src/SurgeRackGUI.hpp
src/UserInteractionsRack.cpp

This commit leads to the system building with either Rack 0.6.2
or Rack 1. The Rack 0.6.2 build currently crashes for a reason
I haven't yet debugged.

Builds with either Rack

---

Makefile
azure-pipelines.yml

This should allow windows to build correctly in the pipelines
although it is still questionable whether it will work.
Closes #15

Makefile rules for Win

---

patches/SurgeFX.vcv
src/SurgeFX.cpp
src/SurgeFX.hpp
src/SurgeRackGUI.hpp

Many things wrong still but you can try the different effect
types in the UI.
Closes #7

Allow you to select an effect type

---

src/SurgeFX.cpp
src/SurgeFX.hpp
src/SurgeRackGUI.hpp

After a conversation with @itsmedavep on slack, we tightened up the
UI quite a bit.

Improve the UI

---

Makefile
src/SurgeRackGUI.hpp

Build appropriate assets for linux to actually link and run with V1
Closes #24

Working library on Linux 

---

patches/SurgeFX.vcv
patches/SurgeFX_v062.vcv
src/SurgeFX.cpp
src/SurgeFX.hpp
src/SurgeRackGUI.hpp

Add gain knobs at the input and output; add gradients to the
graphics; update the patches and so on.
Closes #28

Gain knobs and gradients

---

src/SurgeFX.cpp
src/SurgeFX.hpp

Start doing CV control but then immediatley realize you want
a modulation amount knob. So commit this as a checkpoint and
then go start moving stuff around the UI again.
Addresses part of #8 and #9

The start of CV; plus some string caching

---

Makefile
src/SurgeRackGUI.hpp

Improve the build info with a time and date. Also change the define
path so (I hope) it works with the azure pipeline on windows.
Closes #48

Build Info Improvements

---

plugin.json
res/vectors/SurgeSwitchFull_0.svg
res/vectors/SurgeSwitchFull_1.svg
scripts/g1.sh
src/Surge.cpp
src/Surge.hpp
src/SurgeADSR.cpp
src/SurgeADSR.hpp
src/SurgeRackGUI.hpp

This is a working SurgeEnvelope module but the UI is
incomplete (generously) and there's a lot of copy and
paste with FX. I am committing this code now, though,
so we can have alpha testers build it and then I'll go
back and clean up those problems.
Addresses part of #38

SurgeEnvelope Super-early Alpha

---

patches/SurgeADSR.vcv
src/SurgeADSR.cpp
src/SurgeFX.cpp
src/SurgeRackGUI.hpp

This completes the envelope functionally but the UI is pretty
mediocre. Need some help from the designers. But good enough to
push
Closes #38

A mediocre UI but a usable one.

---

plugin.json
src/Surge.cpp
src/Surge.hpp
src/SurgeModuleCommon.hpp
src/SurgeOSC.cpp
src/SurgeOSC.hpp
src/SurgeRackGUI.hpp

This is an implementation of the OSC which has only
two parameters (OSC type and pitch) exposed. It is
woefully incomplete but I want to checkpoint it into
master for the alpha testers to play with. Addresses issue
#30 partly

Ultra-alpha implementation of the OSC

---

src/SurgeOSC.cpp
src/SurgeOSC.hpp

OSC shows parameters and lets you change and modulate
them. Still a set of things to do including more UI work
but this is a good skeleton. Continues to address #30.

Show parameters in the OSC

---

res/SurgeLogoOnlyWhite.svg
src/SurgeADSR.cpp
src/SurgeFX.cpp
src/SurgeOSC.cpp
src/SurgeRackGUI.hpp
src/SurgeStyle.cpp
src/SurgeStyle.hpp

Refactor the layout to allow style sheet type drawing
mode independently from the widgets themselves.

Refactor the Layout

---

plugin.json
src/Surge.cpp
src/Surge.hpp
src/SurgeModuleCommon.hpp
src/SurgeRackGUI.hpp
src/SurgeWaveShaper.cpp
src/SurgeWaveShaper.hpp

Implement the waveshapre. This control is less interesting
as a module (but it is OK I suppose!) than it is for me
being able to manipulate the sse buffer directly on a pointer
which is also how the filters work. But still: We get a waveshaper
now!
Closes #33

Implement the WaveShaper control

---

src/SurgeWaveShaper.cpp
src/SurgeWaveShaper.hpp

Display the DB; narrow by one screw width; etc.

Small WS tweaks

---

res/SurgeLogoOnlyBlue.svg
src/SurgeADSR.cpp
src/SurgeFX.cpp
src/SurgeOSC.cpp
src/SurgeStyle.cpp
src/SurgeStyle.hpp

@itsmedavep has been sending great looking design prototypes
over the slack channel today. Code a few of the features up,
especially that awesome blue plug area gradient.

Code up some of Dave's ideas

---

README.md
docs/arch.md
src/SurgeADSR.cpp
src/SurgeADSR.hpp
src/SurgeFX.cpp
src/SurgeFX.hpp
src/SurgeModuleCommon.hpp
src/SurgeOSC.cpp
src/SurgeOSC.hpp
src/SurgeRackGUI.hpp
src/SurgeStyle.cpp
src/SurgeStyle.hpp
src/SurgeWaveShaper.cpp
src/SurgeWaveShaper.hpp

Before the code gets into the wild at least clang-format it and
add some documentation on what I did. Closes #59

Cleanup some documentation

---

plugin.json
src/Surge.cpp
src/Surge.hpp
src/SurgeLFO.cpp
src/SurgeLFO.hpp
src/SurgeStyle.cpp
src/SurgeVCF.cpp
src/SurgeVCF.hpp
src/SurgeWTOSC.cpp
src/SurgeWTOSC.hpp

At this point I'm 100% sure this is going to work, so do the tedious
work of framing out the last 3 modules in one go.

Frame out remaining modules

---

src/SurgeFX.cpp
src/SurgeOSC.cpp
src/SurgeRackGUI.hpp
src/SurgeStyle.cpp
src/SurgeStyle.hpp

The screws look like garbage. We will live without them and use
the space for good.

Screw the screws!

---

plugin.json
src/Surge.cpp
src/Surge.hpp
src/SurgeVOC.cpp
src/SurgeVOC.hpp

Update plugin.json with more correct information; add the shell for
the eventual vocoder. Closes #76.

v1 configuration and last of the shells

---

src/SurgeADSR.cpp
src/SurgeADSR.hpp
src/SurgeModuleCommon.hpp
src/SurgeStyle.cpp

I updated the overall style of the widgets to more match the
design implied by @itsmedavep, and totally revamped ADSR
using the new look. Note this also shows that I'm not using
the envelope properly - those times aren't what I'm seeing.
That's another issue though.
Closes #61

ADSR New Look

---

src/SurgeADSR.hpp

Turns out the envelope is a once-every-32 samples timed object.
So do that. Closes #89.

ADSR Envelope Fix

---

src/SurgeADSR.hpp

Thinking about that 32-block loop I realized
1. I should always reset it the moment I get an attack so triggers
don't have an amortized 16 sample delay and
2. I should linearly interpolate between now and next since next
is easy to find (at the cost of having a 32 sample delayed
reaction to parameter changes).

Finalize ADSR

---

src/SurgeADSR.cpp
src/SurgeRackGUI.hpp
src/SurgeStyle.cpp
src/SurgeStyle.hpp
src/SurgeWaveShaper.cpp

1. ADSR labels centered over line
2. WaveShaper looks reasonable, has narrow top mode

Some UI tweaks

---

src/SurgeADSR.cpp
src/SurgeStyle.cpp
src/SurgeWaveShaper.cpp

Narrow ADSR and WS by one screw; cleanup some label sizes; consistent
label capitalization; consistent display color.
All part of #95

Cleanup a few more layout thigns

---

src/SurgeOSC.hpp

The Classic OSC Unison was broken since unison is per voice.
Do a specific change to understand in classic mode when unison
changes I need to re-init my oscillator
Closes #82

Unison in Classic OSC

---

src/SurgeOSC.hpp

If L is hooked up and R isn't then L = (L+R)/2

MONO mode as advertised on the panel

---

src/SurgeModuleCommon.hpp
src/SurgeOSC.cpp
src/SurgeOSC.hpp

It was hard to pick pitch0. Rather than a knob-and-guess like
Fundamental VCO acutally display your note in either frequency
or midi space.

Add a note-or-freq pitch display

---

src/SurgeOSC.cpp
src/SurgeOSC.hpp
src/SurgeStyle.hpp
src/SurgeWidgets.cpp
src/SurgeWidgets.hpp

V0.6.2 streaming of OSC now works. The Widget ButtonBox uses
Daves colors but not edge effects - but they are a bit washed
out I fear.

062 streaming; different button box render

---

src/SurgeWidgets.cpp
src/SurgeWidgets.hpp

Make the butotn box a bit gradienty; move it to the .cpp rather
than the .hpp for convenience. etc..

De-flatten the button box a bit

---

src/SurgeModuleCommon.hpp
src/SurgeOSC.hpp
src/SurgeWTOSC.cpp
src/SurgeWTOSC.hpp

This is an early alpha of the WT OSC. The UI is bad and moreover
it loads inconsistently in all sorts of cases. When you start rack
make sure to press the load button. But it is something we can play with.

Early alpha of the WT OSC

---

src/SurgeWTOSC.hpp
src/SurgeWidgets.cpp

Tiny commit to clean up some INFO cruft so oddy can test without
blowing out his log.

Cleanup some INFO cruft

---

src/SurgeModuleCommon.hpp
src/SurgeWTOSC.cpp
src/SurgeWTOSC.hpp

1: Add a Window or WT mode
2: Do better (but not perfect) at load-wt-on-restore
3: Show the storage location in the log when you start

More WTOSC incremental improvements

---

README.md
src/SurgeWaveShaper.cpp
src/SurgeWaveShaper.hpp

Move the waveshapper to button box UI for mode selection. Clean up the
code a bit including the README state

Move WaveShaper to ButtonBox

---

design/buttonBankInstructions.rtf

sorry for the noise. adding in further color information for the drop shadow and button track

adding drop shadow and button track info

---

src/SurgeStyle.hpp
src/SurgeWaveShaper.cpp
src/SurgeWidgets.cpp
src/SurgeWidgets.hpp

After chatting with @itsmedavep and looking at his designs, I put
together this button bank based on his colors and designs.

Improve ButtonBank

---

plugin.json
src/SurgeFX.cpp
src/SurgeFX.hpp

Add the conditioner effect; clean up a couple of specious log messages
along the way.
Closes #133

Add the Conditioner Effect

---

src/SurgeADSR.cpp
src/SurgeFX.cpp
src/SurgeLFO.cpp
src/SurgeOSC.cpp
src/SurgeRackGUI.hpp
src/SurgeStyle.cpp
src/SurgeStyle.hpp
src/SurgeWTOSC.cpp
src/SurgeWaveShaper.cpp

Have a common base class; have the style mixed in. Still a bit
messy tbh but way better.
Closes #137

Cleanup Layout Code a bit

---

src/SurgeFX.cpp
src/SurgeFreqShift.cpp
src/SurgeModuleCommon.hpp
src/SurgeOSC.cpp
src/SurgeStyle.hpp
src/SurgeWTOSC.cpp

So one by one we have to write panels for the FXes by hand
to make them non-generic. This first one does that for
FreqShift, a relatively compact 5 input effect.

A UI for FreqShift (and some factoring)

---

scripts/BlankFXPanel.cppDontCompile
src/SurgeFX.cpp
src/SurgeRotary.cpp
src/SurgeStyle.hpp

The Rotary Speaker has even fewer parameters than the FreqShift
so use the FS panel as a starting point.

Rotary Speaker Effect gets a panel

---

src/SurgeADSR.cpp
src/SurgeFX.cpp

We want knob / plug / text so make sure everyone does that.
(this commit leaves LFO broken because on a separate branch
I am fixing that properly).

Consistent order

---

src/SurgeLFO.cpp
src/SurgeStyle.hpp
src/SurgeWidgets.cpp
src/SurgeWidgets.hpp

Improve the LFO UI - at least the top half - with a button bank and
switch for uni and so on. Addresses #127

Start of an LFO UI

---

src/SurgeWTOSC.hpp

WaveTable loads of small table on restart are not working. This
hacks around that with a gross but effective hack of forcing a
large table load. We should really fux the underlying but in surge
that causes this. But what to we say to bugs? not today!
Addresses #124 which I should rename after committing this.

Hack-around a bug to load a WT

---

scripts/buildutil.sh
src/SurgeADSR.cpp
src/SurgeFreqShift.cpp
src/SurgeModuleCommon.hpp
src/SurgeRotary.cpp
src/SurgeStyle.hpp
src/SurgeWTOSC.cpp
src/SurgeWTOSC.hpp

1: Show the WT picker much more cleanly
2: Remove the ugly alpha
3: Make roudned corners (and refactor that and apply)
4: Use the slug so buildutil is entirely plugin neutral
5: Skip empty categories
Closes #155

WaveTable UI Improvelemtsn

---

src/Surge.cpp
src/SurgeVCF.cpp
src/SurgeVCF.hpp

I put quite a lot of filter structre in place and want to merge
it into master; but the filter still doesn't work and in this
push I have turned off the nan-spewing noise which it generates.

More work on Filter; but still broken

---

src/SurgeLFO.cpp
src/SurgeLFO.hpp
src/SurgeModuleCommon.hpp

We are almost done with the LFO. This change set implements
1. The correct UI for the top half of the panel
2. Correct behavior when fre-run vs gate
3. TempoSync available everywhere
4. An envelope light

Several LFO Fixes

---

res/presets/EQ/Air.vcvm
res/presets/EQ/Init.vcvm
res/presets/EQ/Mid Cut.vcvm
res/presets/EQ/Smiley Curve.vcvm
scripts/BlankFXPanel.cppDontCompile
scripts/make-fx-presets.py
src/SurgeEQ.cpp
src/SurgeFX.cpp
src/SurgeStyle.hpp

Implement a custom screen for the EQ effect. Implement the
defaults from the configuration.xml

A New Screen for the EQ

---

src/SurgeModuleCommon.cpp
src/SurgeWaveShaper.hpp

Implement the param binding mechanism completely for
the rest of the FX and also the WaveShaper modules.
Basically just the two OSC classes left to go now.

Complete the FX and WS param bindings

---

src/SurgeFX.hpp
src/SurgeLFO.cpp
src/SurgeRotary.cpp
src/SurgeStyle.hpp

Per #149 we need to finish the TempoSync implementation so here
I add it all to the Rotary Panel, which is cool. Then I find out
that Rotary has a bug that it advertises but does not use TempoSync
so I need to fix that. https://github.com/surge-synthesizer/surge/issues/886
is the surge issue for that. Push this anyway since once I fix surge and pull
it will correct this bug.

Add TempoSync to Rotary

---

src/SurgeADSR.cpp
src/SurgeADSR.hpp

This implements temposync for ADSR, completing the temposync sweep.
Closes #149

Complete TempoSync for ADSR

---

README.md
src/SurgeLFO.cpp

Layout the bottom half of the LFO UI in a pleasing way; update the README.

Complete the LFO UI

---

.gitignore
patches/Chorus Delay OSC LFO and ADSR.vcv
src/SurgeChorus.cpp
src/SurgeFX.cpp
src/SurgeStyle.hpp

A panel for the chorus widget which I am happy enough with.
Also some gitignore changes and a few new features in the
base classes to enable it.

A Panel for Chorus

---

README.md
src/Surge.cpp
src/Surge.hpp
src/SurgeBiquad.cpp
src/SurgeBiquad.hpp

The surge filters have 3 flavors which build on each other.
The BiQuad, the QuadUnitChain and the FilterBank. Expose
each eventually but this gives us at least the rudimentary
filter set from the biquad (used for things like the HP filter
on scene).

Introduce the BiQuad filter until

---

Makefile
src/SurgeADSR.cpp
src/SurgeEQ.cpp
src/SurgeFX.cpp
src/SurgeFX.hpp
src/SurgeLFO.cpp
src/SurgeModuleCommon.cpp
src/SurgeVCF.hpp
src/SurgeVOC.cpp
src/SurgeWidgets.cpp

Change makefile rules, surge-rack code and surge code
to greatly reduce the number of warnigns thrown on Linux
and macOS

Warning Supression

---

plugin.json
src/Surge.hpp
src/SurgeADSR.hpp
src/SurgeModuleCommon.cpp
src/SurgeModuleCommon.hpp

ADSR gets polyphony with ths change, as do the base classes needed
to be modified to allow us to start doing poly rack. This gives us
an ADSR which is polyphonic on the Gate input, as you would expect.

First Polyphony in SurgeRack (ADSR)

---

README.md
plugin.json
src/SurgeWaveShaper.hpp

The WS was super easy to make polyphonic once I got the ADSR
cracked, so drop that in this evening also.

Polyphonic Waveshaper

---

azure-pipelines.yml
plugin.json
src/SurgeFX.hpp

Make the FX polyphonic in the simplest way possible, which is:
they are not polyphonic of course but they sum their inputs.

Polyphonic FX

---

plugin.json
src/Surge.cpp
src/SurgeBiquad.hpp

It almost scans like FBN song, but it's really just adding enough
biquads to do polyphonic filtering, and then hooking it up appropriately
with the various inputs and what not. Also turn off the incomplete VCF.

BiQuad is Polyphonic.

---

plugin.json
src/SurgeLFO.hpp

If you are gated you can have polyphonically gated signals which
run an LFO separately for each channel.

SurgeLFO gets polyphony

---

src/SurgeBiquad.hpp

SurgeBiquad polls the control inputs every BLOCK_SIZE and only
recomputes coefficients if there is a change possible.

Surge BiQuad optimization.

---

plugin.json
src/SurgeLFO.hpp

Same trick for ADSR into the LFO

SIMD in the LFO

---

Makefile
plugin.json
src/SurgeWTOSC.hpp

1: WTOSC is polyphonic and works. Needs a touch of profiling but
in M3 about 80% of the time is in the process_block so overhead
isn't that bad
2: Update plugin.json for that, for manual, with correct license
3: Few other cleanups as we get to be release-able

WaveTable Oscillator is Polyphonic

---

src/SurgeBiquad.hpp

Biquad was mis-handling state as part of my optimization; the
optimization under-computed coefficients in some startup
and stream scenarios. Fix.

Biquad was mis-handling state

---

src/SurgeWTOSC.hpp

WTOSC Unison wouldn't restore properly on reload because
I pre-cache the oscillators. Fix that accordingly.

Fix an error with WTOSC Unison

---

src/SurgeWTOSC.hpp

1. lastUnison never reset if no inputs were connected, spewing
messages
2. Save the wavetable loaded by patch and category name meaning
restore keeps sound consistent.

Two WTOSC fixes

---

plugin.json
src/SurgeFX.cpp

Preparing for communit release make 2 changes
1. Improve plugin.json
2. Disable reverb2 and that closes #174
We remember to re-open reverb2 in #210

Preparing for community

---

Makefile
plugin.json
src/Surge.cpp
src/Surge.hpp
src/SurgePatchPlayer.cpp
src/SurgePatchPlayer.hpp
src/SurgeStyle.hpp

This commit sweeps the SurgePatchPlayer at final working into
the master branch. It supports input processing and tempo setting
for temposync as well as traditional midi controls exposed as
appropriate CV inputs.
Closes #171

SurgePatchPlayer module close to final

---

src/SurgeChorus.cpp
src/SurgeOSC.hpp
src/SurgePatchPlayer.hpp
src/SurgeWTOSC.hpp

Clean up our log usage before we do beta1

Remove the majority of rack::INFO calls

---

src/SurgePatchPlayer.hpp
src/SurgeWTOSC.hpp

PatchPlayer and WTOSC would crash in some circumstances
when the underlying wavetable or patch data was missing.
This eliminates those crashes; but if you make dist the
data wasn't missing - but still shouldn't crash!
Closes #219

Dont crash if surge-data is corrupted or missing

---

plugin.json
src/Surge.cpp
src/Surge.hpp
src/SurgeNoise.cpp
src/SurgeNoise.hpp

the surge noise generator is a fairly straight forward
filtered noise, but it is part of quite a few patches,
so make it available as a skinny module here.
Closes #224

Add SurgeNoise

---

README.md
docs/changelog.md

Clean up the README.md; add a changelog
Closes #236

Cleanup the Doc

---

Makefile
azure-pipelines.yml
src/SurgeStyle.hpp
src/SurgeVOC.cpp

In preparation for a release this week upgrade the surge pointer
to 1.6.3 and make the associated adjustments to the makefile and
so on.

Upgrade the Surge pointer to 1.6.3

---

res/skins/classic-skin.xml
src/SurgeRackGUI.hpp
src/SurgeStyle.cpp
src/SurgeStyle.hpp

This version makes a single file which cotnains all the colors used
in surge rather than having them inline. Addresses #251.

Step2 of the reskin project - move colors to a file

---

src/SurgeRackGUI.hpp
src/SurgeStyle.cpp
src/SurgeStyle.hpp

This change, part of the big #251 shift, remembers your skin, but
it does need some refactoring.

Remember your Skin

---

res/skins/Classic.xml
res/skins/Miami.xml
res/skins/NewYork.xml
src/SurgePatchPlayer.cpp
src/SurgeStyle.hpp
src/SurgeWTOSC.cpp
src/SurgeWidgets.hpp

All the colors are in place. So users can go ahead and write
stules for #251 while I fix the last few bugs (the scroll regions
dont invaludate and the 3-position slider isn't orange)

All the colors there; just one or two more bugs

---

res/skins/Classic.xml
res/vectors/SurgeThree_0.svg
res/vectors/SurgeThree_1.svg
res/vectors/SurgeThree_2.svg
src/SurgeADSR.cpp
src/SurgePatchPlayer.cpp
src/SurgeWTOSC.cpp
src/SurgeWidgets.hpp

With this change, everything skinnable is skinned out.
It would be the end of #251 except we are still probably
going to want to tag a few other new skins to that.

Finalized the Skinning Architecture

---

src/SurgeVOC.cpp

While we are getting ready to do #256, turn back the module so
the set is at least reasonable and releasable if we wanted.

Termporarily turn back the half-done new VOC parms

---

azure-pipelines.yml

Was the pipeline really still using 1.0.0?

Upgrade to 1.1.6 SDK

---

src/SurgeWTOSC.hpp

Fix WTOSC Label Reset on SampelRate Change

---

Makefile
azure-pipelines.yml
plugin.json
src/Surge.cpp
src/SurgeFX.cpp
src/SurgeFX.hpp
src/SurgeLFO.hpp
src/SurgeModuleCommon.hpp
src/UserInteractionsRack.cpp

- Update the pointer to 170
- Introduce the Flanger, RingModulator and Reverb2 Units
- Fix various compilation compatabilities and pipeline bitrot

First step in 1.7.0 Upgrade

---

src/SurgeLFO.cpp
src/SurgeLFO.hpp
src/SurgeOSC.hpp
src/SurgeStyle.cpp
src/SurgeWTOSC.hpp

1. Handle the case when a skin isn't loadable. Closes #287
2. Remove the incorrect LFO Retrig
3. HalfRate Filter for the OSCes. Closes #290

A series of smaller fixes

---

Makefile
plugin.json
src/Surge.cpp
src/SurgeFX.hpp
src/SurgeModuleCommon.cpp
src/SurgeModuleCommon.hpp
src/SurgeOSC.cpp
src/SurgeOSC.hpp
src/SurgeRotary.cpp
src/SurgeWTOSC.hpp

- Remove logging messages
- Update the QUantity to use the builtins (but doesn't work for OSC?)
- Pull to 1.7.1
- Upgrade Rotary Module
- Initial pass at activation on OSC but disabled

Checkpoint on the way to 1.7.1

---

azure-pipelines.yml
src/SurgeWTOSC.hpp

Rectify that by dealing with firstTimeIsFromJSON thing
Addresses #301

WTOSC didn't unstream properly in Windows omde

---

src/SurgeOSC.hpp
src/SurgeWTOSC.hpp

Oscillators are now owned by the nvoice array

Fix XT1.1 Memory Management

---

plugin.json
src/SurgeFX.cpp
src/SurgeFX.hpp

Add all the relevant FX

---

Makefile
plugin.json
src/Surge.cpp
src/Surge.hpp
src/SurgeOSCSingle.cpp
src/SurgeOSCSingle.hpp

And expose a (bad UI but good DSP) version of Modern, String, and
Alias along the way

Move towards a Single OSC model

---

Makefile
plugin.json
src/SurgeFX.cpp
src/SurgeFX.hpp

Surge-common can build most of its dsp withuot juce so do so.
Then change the rules here to do that.

Build without JUCE

---

Makefile

Lua also bites the dust for rack!

Build with LUA

---

.github/workflows/native-os-build-plugin.yml

1. Fewer linux apt gets now we don't build juce
2. Cut back on the win -j to hopefully not oom

Github Actions Tweak

---

.gitignore
CMakeLists.txt
src/SurgeOSCSingle.hpp

it's not great. but its better than nothing.

Basic toolign so I can at least use clion on my mac

---

CMakeLists.txt
src/SurgeModuleCommon.cpp
src/SurgeModuleCommon.hpp
src/SurgeOSCSingle.cpp
src/SurgeOSCSingle.hpp

- oscillator way stripped back to minimal
- class kidna in place
- alias and modern and string making sound

Towards a single osc complete model

---

src/SurgeOSCSingle.cpp

SingleOSC can draw the waveform

Draw the Waveform in the SingleOSC

---

src/SurgeVCF.cpp
src/SurgeWidgets.hpp

Can we make a mod-matrix work cleanly? Lets find out!
Modring roughed out. Commit

Modulation Matrix Ring Example

---

src/SurgeOSCSingle.cpp
src/SurgeOSCSingle.hpp
src/SurgeWidgets.hpp

ClassicOsc and only ClassicOsc lays out with many of its
features including a working mod matrix

New Design for Classic; ModMatrix demo

---

Makefile
src/SurgeOSC.hpp
src/SurgeOSCSingle.cpp
src/SurgeOSCSingle.hpp
src/SurgeWTOSC.hpp

Blocksize goes to 8 for the rack build

BlockSize goes to 8

---

src/SurgeOSCSingle.cpp
src/SurgeOSCSingle.hpp

Rough configure String and Modern

---

src/XTWidgets.h

Use the SVG / Bloom Layer Paint for the Mod Button

---

src/VCO.cpp
src/XTWidgets.h

Unison and Octave control implemented for classic, modern,

---

CMakeLists.txt
src/SurgeModuleCommon.cpp
src/SurgeModuleCommon.hpp
src/VCO.cpp
src/VCO.hpp
src/VCOConfig.hpp
src/XTStyle.cpp
src/XTWidgets.h

Huge sets of features missing but they have knobs
and can be modulated and stuff.

All the VCOs are at least roughed out

---

src/VCO.cpp
src/VCO.hpp
src/VCOConfig.hpp
src/XTWidgets.h

This is an intermediar commit around Sine. It
1; Allows activation of the filters
2: exposes the model but not as a menu just as a drag
Want to get it in folks hands for some initial feedback

An Intermediary Commit around Sine

---

Makefile
src/VCF.hpp

- Step one - basic SIMD layout and data structures (but doesn't work yet)
- A mistake coefficient maker pattern and
- hardwired to obxd 24 with
- no mod matrix
like i said, first step only

Towards an implementation of the VCF

---

src/XTWidgets.h

Fix the Mod Ring Radius

---

src/VCO.cpp
src/VCO.hpp
src/XTWidgets.h

Start on Wavetables

---

src/VCO.cpp
src/XTModuleWidget.cpp
src/XTStyle.cpp
src/XTStyle.hpp

Right now we have 4 but we can have more!

LED Color Option next to Skin Option

---

src/VCO.cpp
src/VCO.hpp
src/XTWidgets.h

- A generic preset selctor widget with virtuals
- Positioned for the wavetable
- Menu API basically working
- Jog and Menu order match

Wavetable Selection

---

src/VCO.cpp
src/VCO.hpp

1. Recalc path when wt changes in display
2. Reinit OSC when wt changes in DSP
3. Remove some vestigal ancient code
Upshot is one shots do what they should now

Few WT VCO Fixes

---

src/VCF.cpp
src/VCF.hpp
src/XTWidgets.h

- Type and SubType selectable and joggable
- Type has a menu.
- Subtypes connected. No menu yet.

Editable VCF Type - A Start

---

src/VCF.cpp
src/VCF.hpp
src/XTModule.hpp

- Labels and Tooltips on Gain Corrected
- Correct tooltips on the type and subtype
- Menu on the subtype
- Defaults for subtypes set up and remembered over change

VCF Smaller Tweaks

---

src/VCF.cpp
src/VCF.hpp

And modify surge so we can reuse the exact same one as the virtual instrument

Show the Filter Response Plots

---

src/VCO.hpp
src/XTModule.hpp

so you can pick one and restore a patch later!

WaveTable gets saved in the patch

---

src/VCO.cpp
src/VCO.hpp
src/VCOConfig.hpp

1. Load File works
2. 3D/Not 3D switch on plot works
3. Some other changes preceeding finishing modern

Wavetable/Window VCO Wrapped Up

---

plugin.json
src/SurgeXT.cpp
src/SurgeXT.hpp
src/VCO.cpp
src/VCOConfig.hpp
src/XTModule.hpp

Because that mdoulatino pattern is sweet

Add TWIST to the VCO set

---

src/VCO.hpp
src/XTModule.hpp

A (still non simd) centralized helper implementation of the generic form of the mod matrix; and a port of VCO to use it.

A new, more reasoned, mod matrix

---

src/VCF.cpp
src/VCF.hpp
src/XTModule.hpp

1. The VCF now uses the new modulation mechanism
2. VCF implements gain/mix/drive
3. But this still only works mono->mono; the voice stack for stereo still not coded
4. And comb and vintage model 2 are still broken; not sure why

VCF improvements (mono case only)

---

src/VCF.hpp

Still no stereo though.
Getting close!

Corrected VCF Poly in Mono Mode

---

src/VCF.hpp

1. Animation from Modulation connected
VCF really done.
Add a 'look for performance tweaks' todo list

VCF: Final Pusl

---

src/VCF.cpp
src/VCF.hpp
src/VCO.cpp
src/VCO.hpp
src/VCOConfig.hpp
src/XTModule.hpp

Code reviews, features, poly driver cleaner, animate the filter, label some things. That sort of stuff.

A collection of smaller housekeeping things

---

plugin.json
src/FX.cpp
src/FX.hpp
src/SurgeXT.cpp
src/SurgeXT.hpp

FX DSP is connected

---

plugin.json
src/FX.cpp
src/FX.hpp
src/FXConfig.hpp
src/SurgeXT.cpp
src/SurgeXT.hpp
src/VCF.cpp
src/VCO.cpp
src/XTModuleWidget.hpp
src/XTWidgets.h

Spring Reverb exposed with controls. In doing so create more plumbing to start laying out the FX.

Spring Reverb Exposed; More Plumbing

---

src/VCF.cpp
src/VCO.cpp

Gradient Fills on VCF and VCO curve

---

src/FX.cpp
src/VCF.cpp
src/VCO.cpp
src/VCOConfig.hpp
src/XTModuleWidget.hpp

separate 'modulation/input' layout from 'vco panel' layout

Some Refactors for better Re-Use

---

src/FX.hpp
src/XTModule.hpp

Just like surge proper in the temposynced world we need to modulate the data *copy* not the data itself which does the temposync snap.

Temposync in the presence of Modulation works

---

src/FX.cpp
src/FX.hpp
src/FXConfig.hpp
src/XTStyle.cpp
src/XTStyle.hpp
src/XTWidgets.h

Self-draw panel backgrounds will help with FX. Get it working here. Also fix baseline font clipping.

Ability to self-draw panel backgrounds

---

src/FX.hpp
src/VCO.cpp
src/VCO.hpp
src/VCOConfig.hpp
src/XTModule.hpp
src/XTWidgets.h

- Monophonic MOdulation has a simpler assistant
- Fix a problem with FX modulation
- FM3 gets Absolute toggles on M1/M2
- Support String 2x oversampling option

A collection of changes and fixes

---

plugin.json
src/FX.cpp
src/SurgeXT.cpp
src/SurgeXT.hpp

Because every journey starts with a checklist I guess?

Expose all the FX

---

src/FX.cpp
src/FX.hpp
src/FXConfig.hpp
src/XTWidgets.h

1. Menu for Rotary generalized
2. Power and Extend light in Frequency and Rotary
3. Exciter laid out

Frequency Shifter, Rotary, and Exciter coming along

---

src/Waveshaper.cpp
src/Waveshaper.hpp
src/XTWidgets.h

- Rip out all the old filter nonsense we dont need
- Fix the drive range properly
- Add Biquads for LP/HP
- Fix the double-click-to-reset mystery UI thing

Some Waveshaper Fixes

---

src/FX.hpp
src/LFO.cpp
src/LFO.hpp
src/VCF.hpp
src/VCO.cpp
src/VCO.hpp
src/VCOConfig.hpp
src/Waveshaper.hpp
src/XTModule.hpp
src/XTModuleWidget.hpp
src/XTWidgets.h

1. Dynamic Labels on Twist
2. Unison Cap of 9
3. Rought out LFO parameters a bit but its all off. Check pow vs LUT on waveshaper but leave LUT in play

Some VCO tweaks and fixes

---

src/VCF.hpp
src/VCO.hpp
src/XTModule.hpp

Frequency ranges on VCO and VCF go from -5 to 5 v/oct This allows full range modulation to be 1v/oct

Frequency Ranges Changed - BREAKING CHANGE

---

README.md
src/FX.cpp
src/LFO.cpp
src/Mixer.cpp
src/ModMatrix.cpp
src/TreeMonster.cpp
src/VCF.cpp
src/VCO.cpp
src/Waveshaper.cpp
src/XTModule.hpp
src/XTModuleWidget.cpp
src/XTModuleWidget.hpp
src/XTStyle.cpp
src/XTStyle.hpp
src/XTWidgets.h

- Hover on the mod button and power buttons
- Style can either be global or localized

Style Fixes and Localizations

---

src/FX.cpp
src/VCF.cpp
src/VCO.cpp
src/Waveshaper.cpp
src/XTModuleWidget.hpp

Keybind for modulator select

---

Makefile
README.md
src/FX.cpp
src/FX.hpp

You can display and pick them. You can't, however, see a dirty flag and the params are saved but the identity is not.

First version of FX Presets

---

src/FX.cpp
src/FX.hpp
src/XTModuleWidget.cpp
src/XTStyle.cpp

1. Presets dirty properly
2. Fix a light problem where we used the wrong var

More of the push for presets

---

plugin.json
src/FX.cpp
src/FX.hpp
src/SurgeXT.cpp
src/SurgeXT.hpp
src/XTModule.hpp

Makes the FX Preset implementation complete

Save FX Presets into the JSON

---

src/FX.cpp
src/FX.hpp
src/FXConfig.hpp
src/XTWidgets.h

Align FX labels same way we do VCO labels
Layout Helpers let me do Chorus!

FX Unit Factory - Monday Work

---

src/FX.cpp
src/FX.hpp
src/FXConfig.hpp
src/XTWidgets.h

- Extend butotn, spacing, lots of stuff like that
- Init Preset is correct
- Hooks for dirty and load for specific params from presets
- Few tweaks for preview and for chorus
- Preset load and dirty ont extras. I think Chorus and Resonator are done
- Reverb2 lined up properly

Tuesday FX Work

---

src/FX.cpp
src/FX.hpp
src/XTWidgets.h
src/fxconfig/Chorus.h
src/fxconfig/Exciter.h
src/fxconfig/Resonator.h
src/fxconfig/RotarySpeaker.h
src/fxconfig/SpringReverb.h

Some alternate layouts

---

src/Waveshaper.cpp

Just a little weds morning coding to get this in

Waveshaper Plot

---

src/Waveshaper.cpp
src/Waveshaper.hpp

- Post-filters
- Fix some animation

Finish up the waveshaper

---

src/Delay.cpp
src/Delay.hpp

More work on the standalone delay effect

---

src/Delay.hpp

The DSP is basically wrapped now. Now just the param quantity handlers and the front panel

Add the delay internal modulator.

---

src/Mixer.cpp
src/Mixer.hpp

Start that I can code to. Checkpoint.

Mixer Faceplate Roughed Out

---

res/xt/dark/components/knob-14.svg
res/xt/dark/components/knob-pointer-14.svg
res/xt/light/components/knob-14.svg
res/xt/light/components/knob-pointer-14.svg
res/xt/mid/components/knob-14.svg
res/xt/mid/components/knob-pointer-14.svg
src/FX.cpp
src/FX.hpp
src/XTWidgets.h
src/fxconfig/Chorus.h
src/fxconfig/Reverb2.h

- Chorus and Reverb2 to spec
- Add 14mm knob and spanning label to FX layout protocol

FX Panels to Spec; part 1

---

src/FX.hpp
src/FXConfig.hpp
src/VCO.cpp
src/fxconfig/Distortion.h
src/fxconfig/RotarySpeaker.h

FX Panel More Work - Rotary and Distortion

---

.github/workflows/build-plugin.yml
src/FX.cpp
src/FX.hpp
src/FXConfig.hpp
src/XTWidgets.h
src/fxconfig/Chow.h
src/fxconfig/Exciter.h
src/fxconfig/SpringReverb.h

- Spring Reverb gets knock button
- Exciter in place
- Chow in place
- Mod Button refactored to have a draw buffer
- Toggle PushButton
- Extra schmid triggers
- Actions moved to macos-12

More FX Panel Work

---

src/FX.cpp
src/FX.hpp
src/FXConfig.hpp
src/VCF.hpp
src/Waveshaper.hpp
src/XTWidgets.h
src/fxconfig/Flanger.h

Flanger also brings almost the last of the widget components we need to do the rest of the FX in place also.

Implement Flanger

---

src/VCO.cpp
src/XTModuleWidget.hpp
src/XTStyle.cpp
src/XTWidgets.h

The first of some UI tweaks and fixes from steve

---

src/FX.cpp
src/FX.hpp
src/FXConfig.hpp
src/VCF.cpp
src/VCO.cpp
src/Waveshaper.cpp
src/XTWidgets.h
src/fxconfig/Distortion.h
src/fxconfig/Flanger.h
src/fxconfig/FrequencyShifter.h
src/fxconfig/RotarySpeaker.h

1. Frequency shifter done
2. Some more tweaks and adjustments from Steve
3. Warnigns other than ld macos warning, all squashed

FreqShifter done; Some more tweaks; Squash warnings

---

src/FX.cpp
src/FX.hpp
src/FXConfig.hpp
src/XTModule.hpp
src/XTWidgets.h
src/fxconfig/Chorus.h
src/fxconfig/Chow.h
src/fxconfig/Ensemble.h
src/fxconfig/Exciter.h
src/fxconfig/Flanger.h
src/fxconfig/FrequencyShifter.h
src/fxconfig/Reverb1.h
src/fxconfig/Reverb2.h
src/fxconfig/RotarySpeaker.h
src/fxconfig/SpringReverb.h

- Implement Reverb1 including the four lights
- Make it so we only loop over used params for modulation calculation in FX

Reverb1; Some MOdulation Opt for FX

---

src/VCF.hpp
src/Waveshaper.hpp

For the special case of poly = 1 and stereo, we can save a lot of shuffling in the VCF and Waveshaper with the SSE loads.

VCF and Waveshaper Optimization

---

src/FX.hpp
src/FXConfig.hpp
src/LayoutEngine.h
src/VCO.cpp
src/VCO.hpp
src/XTModule.cpp
src/XTModule.hpp
src/fxconfig/Reverb1.h
src/fxconfig/Vocoder.h

1. Implement the Vocoder
2. Lock a mutex in constructors to make sure we dont make 2 surge storages at a time.
3. Fix Reverb1 Label. Closes #433

Implement vocoder; thread guiard on setup

---

src/FXConfig.hpp
src/fxconfig/RingModulator.h

Ring MOdulator in Place

---

src/DelayLineByFreq.cpp
src/DelayLineByFreq.hpp

No panel SVG background yet and no designed layout Addresses #450

DelayLine by Frequency DSP done and panel functional

---

src/FX.cpp
src/FX.hpp

This seems to implement polyphonic FX and under a cursory test it works (the frequency shifter has multiple frequency bands).
Addresses #451 and after some user testing, we may even want that to be done.

Poly FX Take 1

---

Makefile
src/FX.hpp
src/VCF.hpp
src/Waveshaper.hpp
src/XTModule.cpp
src/XTModule.hpp

ASAN showed an FX bug; Fix it

---

src/Mixer.hpp

Implement modulation in the mixer. This kidna makes the mixer an amazing stereo polyphonic VCA.
Addresses #443

Implement Modulaiton in the Mixer

---

src/Mixer.cpp
src/Mixer.hpp
src/ModMatrix.cpp
src/ModMatrix.hpp

- Faceplate Knobs
- Parameters
- DSP working
Still missing: Matrix Visualization in LCD Area; Profiling; Update SVG for Background
Addresses #443

ModMatrix Step One

---

src/ModMatrix.hpp
src/XTModule.hpp

The poly mod matrix could get a bit heavy. So use some SIMD and some profiling and kill some unused calculations and it is now less heavy by a lot
Closes #438

Mod Matrix CPU enhancements

---

src/VCO.cpp
src/VCO.hpp

the module RMB contains controls for
1. Retrigger from 0 or random
2. Extended and Absolute Unison Ranges if appropriate
3. character filter
4. Oscillator Drift
Addresses #440

Some VCO Improvements

---

src/Mixer.cpp
src/Mixer.hpp
src/ModMatrix.hpp
src/XTModule.hpp

- Parameter values and names correct
- Add a VU meter which can select a poly channel
Closes #443

Complete the mixer

---

src/Delay.hpp
src/DelayLineByFreq.hpp
src/FX.hpp
src/Mixer.hpp
src/VCF.hpp
src/VCO.hpp
src/Waveshaper.hpp
src/XTModule.hpp

FPU Guard just in case

---

src/LFO.cpp
src/LayoutConstants.h
src/LayoutEngine.h
src/XTWidgets.h

LFO is laid out to design. Still lots of DSP and visualization work to do but the knbos are in the right spot and the faders draw (for mid only)

LFO Layout done (mid assets only)

---

src/LFO.h

so you can do all sorts of stuff, inculding LFO feedback!
Addresses #446

Modulation hooked up in the LFO

---

src/LFO.cpp
src/LFO.h
src/VCO.h
src/XTModule.h

Fix windows warnings. Closes #484
Start work on the LFO waveform view. Addresses #446

Fix windows warnings; start LFO waveform

---

src/LFO.cpp
src/LFO.h

Addresses #446
- unipolar mode
- proper gradient fill of the graph
- confirm rate display is correc

More LFO Tweaks

---

src/LFO.h

EOC marker for LFO works

---

src/VCO.h
src/vcoconfig/Alias.h
src/vcoconfig/FM3.h
src/vcoconfig/Modern.h
src/vcoconfig/SHNoise.h
src/vcoconfig/Sine.h
src/vcoconfig/String.h
src/vcoconfig/Twist.h
src/vcoconfig/Window.h

1. Add the params Alias will need for additive UI
2. Clean up some API names to make more sense
With this #440 is good enough for end user beta

More VCO pre-beta work

---

src/Delay.cpp
src/Delay.h

- proper knob and param labels
- improved layout
- display delay times
Closes #442

Finish the delay display things

---

src/LFO.cpp
src/LFO.h

- Deform in the RMB
- Temposync worked on a single timer with an RMB for having rate or env
- IsTriggered checks every sample not every block
Addresses #446

Some LFO work on Sunday afternoon

---

src/LFO.cpp
src/LFO.h
src/XTWidgets.h

1. Direct phase
2. Random initial phase
3. Idependent envelope trigger if you want
4. Draw the handle in-tray more like a 1987 onkyo EQ you purchased at the neighborhood stereo store for $119 and used it to make So sound a lot better, or so you thought, but really you were just cutting the mids on your speakers since they were muddy.
Addresses #446

A variety more LFO features

---

src/LFO.cpp
src/LFO.h

1. Parameters for step editor
2. Some sliders, but the triggers aren't there yet nor ar rotation or endpoints
Addresses #446

LFO Step Editor - Rough First Pass

---

src/LFO.cpp

1. StepSequencer Unipolar editing works fine
2. The line join is set properly so triangle doesn't overshoot
Addresses #446

Two LFO Tweaks

---

src/LFO.cpp
src/LFO.h

1: Trigger on env transition and env end
2: A/B triggers for the Step
3: Trigger pulse appropriate time length
4. Rotate triggers
Addresses #446

Extra Triggers

---

src/LFO.h

MOve modulatino to after the set01 to direct-onto-copy
Addresses #446

Move modulation on LFO

---

src/FX.h
src/VCF.cpp
src/Waveshaper.cpp

Undo for FX Presets, Waveshaper and Filters all
Closes #479

Complete Undo

---

src/XTWidgets.h
src/vcoconfig/Twist.h

Thanks A.Liv!
- DENSITY is the DESTINY for the DENTISTRY : Closes #509
- An invalidation on the handle meant handles didn't snap to top. Closes #508

A few pre-beta fixes

---

src/VCF.h

which crept in when I did partial drive smoothing

Fix a VCF Poly Range Error

---

src/Delay.cpp
src/DelayLineByFreq.h
src/LFO.cpp
src/Mixer.cpp
src/ModMatrix.cpp

1. Option 1234 works for mod selectino everywhere. Closes #518
2. Clamp delay line to avoid noise at extrema. Closes #519

More great finds from A.Liv.

---

Makefile

This *should* work around the cmake problem in the current build environment.

Update Makefile per instructino from @vortico

---

src/Delay.h
src/LFO.cpp
src/LFO.h
src/XTWidgets.h

Thanks Omri!
1. Drag onto mod button and release arms mod button. Fix
2. Delay typeins for rate and mod depth didn't work
3. Delay minimum range was way too high

More Pre-Beta Feedback

---

src/Delay.h
src/FX.h
src/LFO.h
src/Mixer.h
src/ModMatrix.h
src/VCF.h
src/VCO.h
src/Waveshaper.h
src/XTModule.h

1. Add a configParamNoRand which deactivates randomization for a parm
2. Apply it to every mod matrix point
3. Apply it judiciously elsewhere
Closes #524

Limit randomization

---

src/LFO.cpp
src/LFO.h

Trigger always wins though
Closes #529

Add an LFO polyphony mode for if Trigger is not connected

---

src/LFO.cpp
src/LFO.h

You can make it so you still have a monophonic trigger which launches polyphonic LFOs as well as just having free running poly LFOs

LFO Polyphony Broadcast Mode

---

src/Delay.cpp
src/LFO.cpp
src/fxconfig/TreeMonster.h

1. DELAY not Delay
2. TreeMonster lines up with its buddies
3. LFO Gradient in Uni mode goes the right way
4. UNI button should be at - not + 0.5mm

Some last minute tweaks from Steve

---

src/Mixer.cpp
src/Mixer.h
src/VCF.cpp
src/fxconfig/Combulator.h
src/fxconfig/Flanger.h
src/fxconfig/Neuron.h
src/fxconfig/SpringReverb.h
src/vcoconfig/Classic.h
src/vcoconfig/String.h

1. Take almost all the label changes suggested on launch day. Closes #539
2. Update the sst-pugininfra submodule to fix gcc12/win. Closes #540

Labels; GCC12/Win

---

src/VCF.cpp
src/VCO.cpp
src/VCO.h
src/Waveshaper.cpp
src/XTModuleWidget.cpp
src/XTStyle.cpp
src/XTStyle.h
src/XTWidgets.h

- Don't mis-draw the gradient fill on 3D views.
- Optionally turn off knob rings.
- Optionally turn off modulation animation on knob rings.
- Optionally turn off VCF/WS/VCO waveshape animation display
Closes #560
Closes #561
Closes #555

Optional deactivate animation; fix 3d wave view

---

src/LFO.cpp
src/LFO.h
src/XTModuleWidget.cpp
src/XTStyle.cpp

1. EG LFO is continuous when retriggered, not from 0
2. Option lets you go from 0 still
Closes #541

Continuous LFO EG under retrigger

---

src/VCO.cpp
src/VCO.h
src/XTModule.h

In surge we get the HPF to help us out; not so in rack. So sometimes you just wanna block that DC. Use the same one I used with the waveshaper.
Addresses #570
await for user feedback before we close that though

Add an optional VCO DC Blocker

---

Makefile

Per conversation with @cshol, more changes for the rack build environment and its associated cmake flags

Update the Makefile for library compatability

---

plugin.json
src/FX.h
src/LFO.cpp
src/LFO.h
src/VCO.h
src/XTModule.h
src/XTModuleWidget.h

- Set slider min to 0 on uni mode to avoid neg drags. Closes #582
- Correctly update dynbamic names onto name. Closes #573

More smaller issues

---

src/VCO.cpp
src/VCO.h
src/Waveshaper.h
src/XTModule.h
src/fxconfig/Chorus.h
src/fxconfig/Chow.h
src/fxconfig/Combulator.h
src/fxconfig/Distortion.h
src/fxconfig/FrequencyShifter.h
src/fxconfig/Phaser.h
src/fxconfig/Resonator.h
src/fxconfig/Reverb1.h
src/fxconfig/RingModulator.h
src/fxconfig/SpringReverb.h
src/fxconfig/TreeMonster.h
src/vcoconfig/SHNoise.h
src/vcoconfig/Sine.h
src/vcoconfig/Twist.h
src/vcoconfig/Window.h

Makes the UI on the RMB substantially better
Closes #589

Move to configSwitch from configWithOnOffQuantity

---

src/LFO.cpp
src/LFO.h
src/LayoutEngine.h
src/VCO.cpp
src/VCO.h
src/XTWidgets.h

- Halo and Ring clipping in a couple of spots fixeds. Closes #592
- Re-Init on Wavetable Change restored. Addresses #584
- Factor the Wavetable menu so it appears both in the preset selector and also in the main menu. Closes #588
- Relabel LFO TRIG. Closes #587 and addresses #586

Some more UI and User Feedback things

---

src/VCO.cpp
src/VCO.h

- add ability to load untagged waves with a user provided sample frame rather than defaulting to oneshot
- add a load waveedit menu item since that is common in rack land
- add submenus for all the size from 64-4096

WaveTable Loading for common cases a bit better

---

src/VCO.cpp
src/VCO.h
src/vcoconfig/Alias.h

Basically implement the Alias Harmonic Editor.
1. Add an API to draw an edit button which is config controlled
2. Editor Swap-out for Display area works
3. And alias editor is done
Closes #553

The Alias Harmonic Editor

---

src/LFO.h

Not useful for much other than me banging my head
against #607

Make the LFO FromZero mode the exact surge mode

---

src/VCF.cpp
src/Waveshaper.cpp

Thanks lars! Sharp eyes!
Closes #611

Checkmarks on VCF and WS selector menus

---

src/XTModuleWidget.cpp
src/XTStyle.cpp
src/XTStyle.h
src/XTWidgets.h

per steve's specs. Closes #565

Shadow Implementation

---

src/XTStyle.cpp
src/XTStyle.h
src/XTWidgets.h

As opposed to black-on-black which was hard to see. Closes #627

High Contrast Slider (LFO EG) fill is white again

---

src/fxconfig/Vocoder.h

Oops! Good we caught that before release

Fix Vocoder Labels

---

src/XTModuleWidget.h
src/XTWidgets.h

Per a request from @vortico and @pgatt
Closes #640

Change frame-based timers to clock-based timers

---

docs/changelog.md
src/EGxVCA.cpp
src/EGxVCA.h
src/XTWidgets.h

1. Temposync and associated modulation works
2. Layout for the display area with coming soon glyphs so people at least know it is coming soon

EGxVCA work plods on

---

docs/dev/Blank12.cpp
docs/dev/Blank12.h
plugin.json
src/QuadAD.cpp
src/QuadAD.h
src/SurgeXT.cpp
src/SurgeXT.h

QuadAD has zero function of course! It's just a stub so I can make and think about the base stub for a 12hp this morning

Add a Blank12 starting point; Add a blank called quadAD

---

docs/changelog.md
docs/dev/Blank12.h
src/EGxVCA.cpp
src/EGxVCA.h
src/QuadAD.cpp
src/QuadAD.h
src/XTWidgets.h
x

- Some memory cleanups on EGxVCA. Addresses #598
- Params and Panel roughed out for QuadAD. Addresses #633
- DSP and Polyphony for Quad AD also working, except digital slopes

Work on QuadAD and EGxVCA

---

src/QuadAD.h

If you disconnected an intermediate which was in the sum the poly count went wrong. So cache connectivity/trigger graph every 8 samples and so on instead (which also improves CPU)

Fix a trigger mode issue with QuadAD and poly

---

src/LFO.cpp
src/LFO.h
src/NBarEditorWidget.h
src/XTWidgets.h
src/vcoconfig/Alias.h

Add a custom widget for NBar edits with appropriate gestures. Still a bit of straggler work to do which I will put in a new issue, but this is a major improvement
Closes #559
COmplete step 1

Re-implement the LFO and ALias step edits

---

src/QuadLFO.cpp
src/QuadLFO.h
src/dsp/SimpleLFO.h

- A simple LFO in the codebase using the project forward and interp
- Parameters hooked up
- Todo list in place

More work on Quad LFO

---

src/VCO.h

Some broken environments lack wavetables and throw errrors as a result. Make those errors more sociable by (1) initing sine and (2) not streaming a broken wavetable.
This probably closes #689

Absent WaveTables, swap to sine

---

Makefile

- surge changes to turn off uneeded juce formats
- surge changes to merge riscv and wasm juce diffs
- makefile change to leave out lua src which we don't use

Final tweaks to integrate the weekend work

---

src/LFO.cpp
src/LFO.h

Does randomization change shape outside the step? Make it so *you* decide. Closes #684

Randomization Shape Change control

---

src/VCF.cpp

This PR makes VCF work in web-assembly.
For web-assembly target, using emscripten, using threads is not always wanted.
Threads in web-assembly require a secure connection with special headers, which makes local deploys quite difficult.
What I have been doing for Cardinal is setup timer intervals anytime a thread is used.
There is no well defined API for this on Cardinal side yet though, so a bit of custom code is necessary for now.
Which might be handy if anyone else is building surge-xt-rack in web-assembly too, outside of Cardinal.
Sadly VCF still throws an error later on, I suspect due to some advanced SSE features not all being available in the browser context. But that would be on the surge subproject, not surge-rack.

VCF: Use a timer interval instead of threads for emscripten

---

src/QuadLFO.cpp
src/QuadLFO.h
src/XTModuleWidget.h
src/XTWidgets.h
src/dsp/SimpleLFO.h

1. Show curves and have the display area generally there
2. Modify the LFO for a display mode and stuff
3. Modulation animation support
4. Mode preset selector (does nothing yet)
5. Add a generic dirty helper to make it less tedious
etc..

A variety of QuadLFO UI Work

---

src/QuadLFO.cpp
src/QuadLFO.h
src/dsp/SimpleLFO.h

- Menu item
- Can follow trigger
- Needs profiling

Polyphony for QuadLFO

---

src/QuadLFO.h
src/dsp/SimpleLFO.h

Here you go. Phase mode it is. Still needs loads of work.

Start on modes; do phase mode

---

src/QuadLFO.cpp
src/QuadLFO.h
src/dsp/SimpleLFO.h

Use rate as [0,1] and contextually display normal values Implement properly for the two implemented modes and tie out with references from bog etc
Animate the phase modulation offset in mode 2
Typeins work
Little cleanups

Units on Params starting to be correct

---

src/QuadLFO.h

- Rough out ratio mode
- Update todo list
- Re-plan the innards

Rough out ratio mode; re-plan the innards

---

CMakeLists.txt

1. Plugin.dylib links the surge rack stuff
2. A quick install target

A quick fix to the CMake Approach

---

Makefile

Revert bd5a250291acf270b38bf447154d1b1b49bcf2e7 for Makefile

Quickly revert Makefile (but not Cmake) changes

---

src/LayoutEngine.h
src/QuadLFO.cpp
src/QuadLFO.h
src/dsp/SimpleLFO.h

- Move to block processing of size 8 makign CPU really efficent
- Typeins and so on for all the modes
- Factoring so there's loads more code shared
- Freeze and Reverse in place
- Update todo list which is now just clocks and spread mode

More Quad LFO Advances

---

src/QuadLFO.cpp
src/QuadLFO.h
src/dsp/SimpleLFO.h

Quadrature Mode in place

---

.github/workflows/code-checks.yml
src/QuadLFO.cpp
src/QuadLFO.h
src/XTWidgets.h

- Entangled Mode in place
- Some other cleanups on indicies and code and workflows

Entangled Mode; some other cleanups

---

README.md
src/QuadLFO.h
src/dsp/SimpleLFO.h

Quad LFO Amplitude changes

---

src/QuadAD.cpp
src/QuadAD.h
src/QuadLFO.h
src/dsp/ADAREnvelope.h
src/dsp/SimpleLFO.h

- Some initialization in QuadLFO
- QuadAD looping works bidirectionally
- QuadAD Polyphony correct
- QuadAD Proper drawing items for forward/backwards triggers

More Work on Quads

---

.github/workflows/make-extra-content.yml
src/VCO.cpp
src/VCO.h

1. Have a "download" option (ifdefed out)
2. Actually do the download
3. Make the content action manual only
The big thing now is adding the extra wt path to the factor list in surge proper and so on.
Addresses #710

Further changes for download content

---

.github/workflows/make-extra-content.yml
src/QuadAD.cpp
src/QuadAD.h
src/QuadLFO.h
src/XTWidgets.h

Just pushing it up so Steve can run it basically if he wants. Starting layout, little glyph for slopes, etc... but really gotta run so push on a sunday morning in the dev period.

Some incremental morning Quad AD work

---

CMakeLists.txt
RackSDK.cmake

Upgrade a collection of settings to have a proper interface for RackSurge in CMake etc...

manage target dependencies with interface libraries

---

src/QuadAD.cpp
src/QuadAD.h

Only thing left on this module is the cycle trigger shutoff logic

Quad AD Front Panel Rendering ready for design review

---

CMakeLists.txt
Makefile
RackSDK.cmake

I also fixed the command, because on windows it was not working.
You would need to add these changes to your BaconPlugs by yourself this time.

moved quick_install target into RackSDK.cmake

---

CMakeLists.txt
Makefile
RackSDK.cmake
docs/changelog.md
src/EGxVCA.h
src/QuadAD.h
src/QuadLFO.h

- MakeFile dep depends on CMakeList
- move todo lists to github issue tracker
- update changelog

Some code and doc clenaup

---

src/EGxVCA.cpp
src/EGxVCA.h
src/QuadAD.cpp
src/QuadLFO.h
src/XTModule.h
src/XTModuleWidget.h
src/XTWidgets.h
src/dsp/ADSRDAHDEnvelope.h

- Re-implement the envelope locally with better sample accuracy for attack
- Add the DAHD mode and morph param start
- Add an EOC out
- Parameters working with switches
- Layout starting to get clener
- Curve Types work
- Correctly draw the glyphs for the shapes
- Draw that VGA Curve
- Set bounds for ctenvtime to 10s top

Substantial push on EGVCA

---

RackSDK.cmake
src/Delay.h
src/EGxVCA.h
src/TemposyncSupport.h
src/XTModule.h
src/dsp/ADSRDAHDEnvelope.h

Start some common factoring also. And fix a cmake message.

Implement TempoSync for EGxVCA

---

src/EGxVCA.h
src/dsp/PanLaws.h

Just lifted them from mixmaster tbh

Equal Power pan law (stereo and mono) in EGxVCA

---

src/QuadLFO.cpp
src/QuadLFO.h
src/dsp/SimpleLFO.h

Two interesting extra modes
Also get sample accurate pulse and S&H onset.

Quad LFO gets Down Ramp and Random trigger

---

src/QuadAD.cpp
src/QuadAD.h
src/XTWidgets.h
src/dsp/ADAREnvelope.h

- it's really just display and maybe some typeins left
- So added a beta label also

Quad AD Cycle and Cancel and Sum all fixed

---

CMakeLists.txt
plugin.json
src/DelayLineByFreqExpanded.cpp
src/DelayLineByFreqExpanded.h
src/LayoutEngine.h
src/SurgeXT.cpp
src/SurgeXT.h

A radical expansion of the tuned delay to add inline filters, feedback, and stereo field tuning, along with modulation of each of the parameters
Addresses #646

Modelling Delay Alpha

---

src/EGxVCA.h
src/QuadLFO.h
src/TemposyncSupport.h

QuadLFO gets clock based temposync in the relevant modes. Still need to do some label work in the display for it.

QUad LFO TempoSync

---

plugin.json
src/DelayLineByFreqExpanded.cpp

So push this up for the nightlies

Tuned Delay + is the name we settled on

---

src/DelayLineByFreqExpanded.cpp
src/EGxVCA.h
src/QuadAD.h
src/QuadLFO.cpp
src/QuadLFO.h
src/TemposyncSupport.h
src/XTModule.h

- QLFO gets final bugs fixed
- EGxVCA gets labels and so on but still needs pan work
- TD+ gets an unused LCD area
- Changelog updated
Basically ready for a pre-christmas beta on community

QLFO; EGxVCA; DelayLine to almost-beta

---

docs/changelog.md
src/DelayLineByFreqExpanded.cpp
src/DelayLineByFreqExpanded.h

- VU Meter which works pretty well
- Few UI and other tweaks
- Remove beta label
Clsoes #646

Wrap up Tuned Delay +

---

src/Delay.h
src/DelayLineByFreq.h
src/DelayLineByFreqExpanded.h
src/EGxVCA.h
src/FX.h
src/LFO.h
src/Mixer.h
src/ModMatrix.h
src/QuadAD.h
src/QuadLFO.h
src/VCF.h
src/VCO.h
src/Waveshaper.h
src/XTModule.h

Second try, obviously. This one *actually* closes #707 properly.

FX Scans Presets not Wavetalbes

---

.github/workflows/code-checks.yml
.github/workflows/make-extra-content.yml

Somehow these have been missed.

Update workflows to Rack SDK 2.2.2

---

src/QuadLFO.cpp
src/QuadLFO.h
src/TemposyncSupport.h

1. Temposync works in Entangled mode
2. Way better temposync display and other display options
3. Temposync selection menu
Addresses #620

A variety of QLFO updates

---

src/Delay.cpp
src/Delay.h

as well as hard clip
Addresses #777

Delay line gets a 10v soft clip

---

RackSDK.cmake
src/QuadAD.cpp

Steve's final UI adjustments. Remove beta tag. Closes #633

Quad AD Final UI Changes

---

src/DelayLineByFreqExpanded.cpp
src/DelayLineByFreqExpanded.h

1. Label from ATTEN to LEVEL
2. Level in dB
3. Rename range names
Closes #790

Delay + Attenuation Label

---

src/DelayLineByFreqExpanded.cpp
src/DelayLineByFreqExpanded.h

Add TD+ Delay Clamps at 20, 10 or 5V

---

src/LFO.cpp
src/NBarEditorWidget.h
src/vcoconfig/Alias.h

Labels, Presets, Default and Zero setters. That sort of thing.
Closes #683

Final bar gestures

---

src/DelayLineByFreqExpanded.h

1. Feedback is applied cubically
2. Readout in decibels
3. Better attenuated range

Some TunedDelay+ callibration

---

src/DelayLineByFreqExpanded.h

How many will we try I wonder? Lets see how this one feels.

Yet another Delay+ Attenuation Callibration

---

docs/changelog.md
src/LFO.cpp

Also update changelog
Closes #799

Shrink LFO arrows for rotation

---

src/QuadLFO.cpp
src/QuadLFO.h

Also remove beta label
Closes #620

Quad LFO allows Ratio Rate modulation with snap

---

src/EGxVCA.cpp
src/dsp/ADSRDAHDEnvelope.h

- Final graphics positioning cleanup and sizing
- fix an occasional analog DAHD booger at start of sustain
Closes #598

Complete EGxVCA

---

src/XTModule.h

Fix a typein modulation range on extended pars

---

src/QuadLFO.h

Range should be -1,1 for both.

Entangled deform and amplitude need range clamps

---

src/EGxVCA.cpp
src/QuadAD.cpp
src/dsp/ADAREnvelope.h
src/dsp/ADSRDAHDEnvelope.h

Turn off the Analog Envelope Speed controls

---

src/QuadLFO.cpp

Draw the LFO curves on layer 1.

---

src/EGxVCA.cpp

Match signal flow and display rodering namely -> env -> pan. -> level
Closes #821

Move the EGVCA panel controls to match signal and display

---

src/EGxVCA.cpp
src/EGxVCA.h
src/QuadAD.cpp
src/QuadAD.h
src/XTModule.h

1. All envelopes now live in basic-blocks with appropriate types
2. Complete slow mode. Addresses #832

Complete refactoring of envelopes to basic-blocks

---

CMakeLists.txt

Rather than surge. Closes #848

Use SIMDE from RACK_SDK_DIR

---

src/LFO.cpp

Tried to also make the sentence shorter.

Clarify "Set EG to zero..." menu wording

---

src/EGxVCA.cpp
src/EGxVCA.h

I copied the wrong default from mixmaster (sigh) so
1: Add the right default here (equal power stereo) and
2: Make the true panning an option
This will change the default panning.
Closes #849

Add EGxVCA Pan Laws

---

src/LFO.cpp

LFO Step Label says SHUFFLE not PHASE dynamically

---

src/vcoconfig/Modern.h

This would result in incorrect unstreams of MOMT_SINE
Closes #879

Set range for Modern sub-type properly

---

src/VCO.cpp
src/VCO.h
src/XTModule.h
src/vcoconfig/Twist.h

Make Twist optionally exclude Engine from Randomization

---

src/Waveshaper.cpp
src/Waveshaper.h

with an option to turn it off
Addresses #883. Still thinking a bit though

Show the transform and response in waveshaper

---

src/XTWidgets.h

Just like Knobs, Sliders now show anumation for modulation using the value display line.
Closes #868

Sliders add Animation

---

CMakeLists.txt
plugin.json
src/Mixer.h
src/VCO.h

1. Upgrade the Surge to latest 1.3 head (not yet stable)
2. Fix the various places where surge api has shifted
3. Move the sst-basic-blocks dependency to the surge one to avoid dup
Here we go!

Start the 2.2 Rack (1.3 VST) lifecycle

---

CMakeLists.txt
plugin.json
src/DigitalRingMod.cpp
src/DigitalRingMod.h
src/FX.cpp
src/SurgeXT.cpp
src/SurgeXT.h
src/XTWidgets.h

- Digital Ring Mod
- Bonsai
- Nimbus (Addresses #844)
All stubbed out with screens, and Bonsai and Nimbus actually run effects.

Shells of new modules

---

.gitmodules
CMakeLists.txt
src/Delay.h
src/EGxVCA.h
src/FX.h
src/LayoutEngine.h
src/VCF.h
src/VCO.h
src/Waveshaper.h
src/XTWidgets.cpp
src/XTWidgets.h

1. Connect to MixMaster/AuxSpander
2. Connect to your neighbor
Addresses #829

Module Connecting RMB functions

---

src/FXConfig.h
src/fxconfig/Nimbus.h

It's just clouds, but its easy to add and makes it consistent with the other FX modulation polyphony and so on.
Closes #844

Add the working Nimbus module

---

src/DigitalRingMod.cpp
src/DigitalRingMod.h
src/LFO.h
src/XTWidgets.h

Inputs, outputs, lcds, params. Just no DSP yet

CXOR / Digital Ring Mod Screen Laid Out

---

plugin.json
src/DigitalRingMod.cpp
src/DigitalRingMod.h

A working version of the CXOR module

---

.github/workflows/build-plugin.yml
Makefile
RackSDK.cmake

- plugin-arm to plugin
- modify github workflows
- no functional changes

Patch for the 2.4.0 SDK

---

CMakeLists.txt

Turn off a clang-15 arriving warning on macos

---

src/VCO.cpp

Following https://github.com/surge-synthesizer/surge/pull/7158

Update VCO display to use HR Filter

---

CMakeLists.txt
plugin.json
src/LayoutEngine.h
src/SurgeXT.cpp
src/SurgeXT.h
src/UnisonHelper.cpp
src/UnisonHelper.h

Add a shell for the Unison Helper. Addreses #804. Pull surge further along the 1.3 path, and make the bnaks work so they compile again. Also make it so you can make a one in two out module with the layout engine

Unison Shell; Update Surge; Fix Blanks

---

src/UnisonHelper.cpp
src/UnisonHelper.h

It actually drives Bog with unison properly.
Addresses #804

More UnisonHelper progress

---

.github/workflows/build-plugin.yml
.github/workflows/code-checks.yml
.github/workflows/make-extra-content.yml
Makefile
RackSDK.cmake

Hi,
I updated all the build related files with required changes for the latest Rack-SDK. 
It is all working also for the latest Rack 2.4.1 SDK and the latest docker toolchain.

updates for Rack-SDK 2.4 changes

---

docs/changelog.md
docs/nightlychangelog.md
src/UnisonHelper.cpp
src/UnisonHelper.h

Just needs LCD layout now, really. Also update the changelog and add a nightly changelog

Unison gets Character Filter; Nightly Changelog

---

src/DigitalRingMod.h
src/UnisonHelper.cpp
src/UnisonHelper.h

Also add bypass to Digital Ring Mod

Unison Module - everything except UI works

---

src/UnisonHelper.cpp
src/UnisonHelper.h
src/XTWidgets.h

Use Andreyas great idea to add a lo/hi pass
Make modulation work
Add the info label
Test some voice edge cases
Closes #804

Finish the Unison Module

---

src/UnisonHelper.cpp
src/UnisonHelper.h

1. Label the inputs and outputs with config (duh)
2. Add a single box
3. Update the RTN to VCO label

Some more unison tweaks

---

docs/nightlychangelog.md
plugin.json
src/Mixer.cpp
src/SurgeXT.cpp
src/SurgeXT.h
src/XTWidgets.h

Because sometimes you want your mixer. To have sliders.
Closes #845

Add a Mixer with Sliders

---

src/UnisonHelper.h

1. Don't re-hook to a full spot
2. Rotate through rack colors for cable pairs
Addresses #829

Update cable connectivity auto-tools

---

docs/nightlychangelog.md
src/EGxVCA.cpp
src/EGxVCA.h
src/LayoutEngine.h
src/XTModuleWidget.h

Per #890, trigger on start of phases or on all transitions or on end of cycle, controlled by RMG

EGxVCA alternate EOC signals

---

src/VCO.cpp
src/XTModule.h

Allow a Documents/Rack2/SurgeXT/UserWavetables dir for rack only wts

---

src/EGxVCA.cpp

once you see it you ahve to fix it
Closes #941

Fix EGxVCA Alignment

---

src/VCO.h

Cache the WT -> Base64 Conversion so that we only make it when the WT changes, and not when we do every auto-save.
Closes #893

Cache WT -> Base64 Conversion

---

CMakeLists.txt
src/FX.h
src/fxconfig/RingModulator.h

Closes #454
RM has sideband inputs which can replace the internal sine osc

Ring Modulator gets external input; Vocoder Level Fixed

---

src/DelayLineByFreq.cpp
src/DelayLineByFreq.h
src/DelayLineByFreqExpanded.h
src/DigitalRingMod.cpp
src/DigitalRingMod.h
src/LayoutEngine.h
src/Mixer.cpp

This makes sure everyone has appropriate neighbor connectors, mixmaster connectors, and that the UI is appropriate.
Closes #945
Addresses #829

FInish connector stuff for 2.2

---

docs/nightlychangelog.md
src/LayoutEngine.h
src/VCO.cpp
src/XTWidgets.h
src/vcoconfig/FM2.h
src/vcoconfig/FM3.h
src/vcoconfig/Sine.h

Sine was extended by default so it doesn't get a button
Also pull surge to the 1.3 release candidate
Closes #911

Expose FM2/FM3/Sine Extended and Vintaged

---

src/fxconfig/Nimbus.h

Closes https://github.com/surge-synthesizer/surge-rack/issues/931

Nimbus Finished Up Tweaks

---

docs/nightlychangelog.md
src/VCF.cpp
src/VCF.h
src/VCO.cpp
src/VCO.h
src/Waveshaper.cpp
src/Waveshaper.h

Basically there's a menu where you get to pick which curbve you are showing. Handy! Closes #855

VCF, VCO, WS can choose curve poly chan

---

docs/nightlychangelog.md
src/FX.h
src/fxconfig/SpringReverb.h

FX NaN protection; Activated for Spring Reverb

---

src/FX.h
src/XTWidgets.h
src/fxconfig/RingModulator.h

1. Connect inside this row
2. FX sideband inputs are connectable inputs

Connector module upgrades

---

src/XTWidgets.h

- pull rackhelpers to head
- remove a warning on xtmodule

Final 2.2.2 tweaks

---

src/FX.h

My bet is this also addresses #989 startup poly problem

Reset I/O buffers when we re-init effects

---

.github/workflows/build-plugin.yml
.github/workflows/code-checks.yml
.github/workflows/make-extra-content.yml

update workflow actions

---

RackSDK.cmake

Move the static declartion to before the plugin lib
