surge-synthesizer/surge-rack

- Makefile
- src/SurgeFX.hpp
- src/SurgeRackGUI.hpp
Set up the makefile and include the missing headers so that we also
get a clean 0.6.2 build on Linux. Haven't tested if this works, but
have confirmed that make dist results in an asset.
Closes #14 (build on linux)
> Builds Rack 0.6.2 Linux

- Makefile
- azure-pipelines.yml
Final fixes to make Rack build in the CI Pipeline on Windows
(which basically amount to "don't assume the C++17 filesystem
API is there; and g++ on windows is not the same as WINDOWS
in surge). So a set of directies in surge and make rules here and
we are good.
> Final Fixes for CI Pipeline

- Makefile
- azure-pipelines.yml
- patches/SurgeFX.vcv
- patches/SurgeFX_v062.vcv
- src/SurgeFX.cpp
- src/SurgeFX.hpp
- src/SurgeRackGUI.hpp
This diff does a few small things to clean up the plugin
- It updates the surge submodule to 1.6 beta 9
- It deals with the final string cache for effect name
- It adds screws
- It adds a version displayed in the UI
- It lays out the effect name control in a non random way
CLoses #46 Version in the UI
Closes #8 dirty string caches
> Layout; Screws; Versions

- Makefile
- scripts/g1.sh
- src/SurgeFX.hpp
SurgeStorage reads configuration.xml and wavetables from
the plugin zip now, not from the surge install you happen
to have.
Closes #25
> SurgeStorage reads from the plugin

- src/SurgeADSR.cpp
- src/SurgeADSR.hpp
- src/SurgeFX.cpp
- src/SurgeFX.hpp
- src/SurgeModuleCommon.hpp
- src/SurgeRackGUI.hpp
This is a technical diff which came from having two modules and
wanting to reduce copied code. There's more to come but
1. Ripped out the TBase stuff which doesn't apply here like it does
in BaconPlugs
2. Add a common base class for modules
3. Add a background draw hook
4. Add a string cache helper and use it once (but not everywhere) in FX
5. etc...
Closes #56 although I'm sure there's lots more to do...
> Do some refactors now I have two modules

- src/SurgeADSR.hpp
- src/SurgeFX.hpp
- src/SurgeModuleCommon.hpp
- src/SurgeOSC.hpp
1: For processors which have block sizes, only update the
parameters when we calculate a block, not on every step
2: For processors using surge storage, only copy the necessary
subset of params from local to buffer, not the entire scene or
global set.
3: Don't run the oscillator if you don't have anything connected
to the output
Closes #73
Closes #80
> Three core performance improvements

- src/SurgeFX.hpp
- src/SurgeModuleCommon.hpp
FX Label Invalidation was incorrect, over-invalidating labels
leading to 50% of the processing time in FX being sprintf.
This fixes that problem.
Closes #67
> FX Label Invalidation

- src/SurgeWaveShaper.cpp
With 0.6.2 initialization order misplaced the WS i/o.
> WS error fixed

- src/SurgeLFO.cpp
- src/SurgeLFO.hpp
- src/SurgeModuleCommon.hpp
- src/SurgeOSC.cpp
- src/SurgeRackGUI.hpp
- src/SurgeVCF.cpp
- src/SurgeVOC.cpp
- src/SurgeWTOSC.cpp
With my new clever classes I had mis-owned a label cache
when module was null, causing a reliable crash on linux
and a reliable mis-draw in the preview pane on mac.
> Fix a memory error

- src/SurgeOSC.cpp
- src/SurgeOSC.hpp
- src/SurgeRackGUI.hpp
- src/SurgeStyle.cpp
- src/SurgeStyle.hpp
- src/SurgeWidgets.hpp
This commit introduces the SurgeButtonBank widget, which is
fully functional but has an incomplete draw look and feel.
Using that widget, we re-panel the SurgeOSC to be way more
compact and obvious. At the same time, fix the problem with
OSC type switches resulting in mis-rendered parameters (which
Closes #68).
> ButtonBank Alpha; New OSC Panel

- src/SurgeModuleCommon.hpp
- src/SurgeOSC.hpp
When switching between oscillator types, set up the OSC in the
default state upon initialization.
Closes #74
> OSC Default Values

- src/SurgeADSR.hpp
- src/SurgeFX.hpp
- src/SurgeLFO.hpp
- src/SurgeModuleCommon.hpp
- src/SurgeOSC.cpp
- src/SurgeOSC.hpp
- src/SurgeRackGUI.hpp
- src/SurgeStyle.cpp
- src/SurgeVCF.hpp
- src/SurgeVOC.hpp
- src/SurgeWTOSC.hpp
- src/SurgeWaveShaper.hpp
This commit does two big things
1: It adds knob memory per oscillator type, adjusts knobs as
you switch, detects if you are unstreaming from json to
override defaults, moves knobs in v0.6.2 etc...
2: Takes the debug version info off the front panel and puts it
in the log; adds a getName to every SurgeModuleCommon
> Knob Memory and Motion; Better Borders

- src/#SurgeOSC.hpp#
- src/SurgeModuleCommon.hpp
I added a custom streaming and unstreaming class for all surge-rack
instances through the SurgeModuleCommon class; along with virtual
functions if particular folks want to add extra stuff. I implement
the "comment" and "buildVersion" tag in all our data fields.
> Custom streaming for all surge-rackers

- src/Surge.hpp
- src/SurgeModuleCommon.hpp
- src/SurgeWidgets.cpp
- src/UserInteractionsRack.cpp
This handles INFO refering to logger::log rather than rack::logger::log.
https://github.com/VCVRack/Rack/issues/1276
Closes #119
> INFO definition changed in v1

- src/SurgeOSC.hpp
- src/SurgeWTOSC.hpp
1: WTOSC loads your wavetable on load
2: OSC and WTOSC have the correct R channel
> Some small OSC fixes

- Makefile
v1-gpl reqires -pthread for modules explicitly now. Adjust. Closes issue #122
> Add -pthread on linux for v1-gpl

- res/presets/OSC/Init_Classic.vcvm
- res/presets/OSC/Init_FM2.vcvm
- res/presets/OSC/Init_FM3.vcvm
- res/presets/OSC/Init_Noise.vcvm
- res/presets/OSC/Init_Saw.vcvm
- res/presets/OSC/Init_Sine.vcvm
- res/presets/OSC/Init_Square.vcvm
- scripts/g1.sh
- src/SurgeADSR.hpp
- src/SurgeModuleCommon.hpp
This commit implements factory preset loading for each module in a
generic way in Rack V1. Basically each module (a SurgeModuleCommon
subclass with a getName()) scans "res/presets/getName()" for presets
at the outset. So preset creation is simply creating that directory
and pushing vcvm files. To get started I included @oddy.o.trax's OSC
inits.
Closes #98
> Implement Presets

- scripts/g1.sh
- src/SurgeFX.cpp
- src/SurgeFX.hpp
1. FX never implemented "or mono" correctly
2. FX had Left and Right backwards
This change corrects both.
Closes #11
Closes #54
> FX stereo corrections

- src/SurgeFX.cpp
- src/SurgeFX.hpp
- src/SurgeModuleCommon.hpp
- src/SurgeStyle.hpp
This change implements temposync support for the effect route.
The FX generic panel gets a clock input and tempo-sync aware
parameters get a toggle. Works exactly as you'd expect.
Closes #51
> TempoSync for all effects

- plugin.json
- src/Surge.cpp
- src/Surge.hpp
- src/SurgeClock.cpp
- src/SurgeClock.hpp
- src/SurgeModuleCommon.hpp
It's useful to have a widget which generates both a gate and
a consistent CV for a clock. So add one in surge even though
it isn't really surge-y
> Add a simple skinny clock

- Makefile
- scripts/buildutil.sh
- src/Surge.cpp
- src/Surge.hpp
- src/SurgeFX.cpp
- src/SurgeFreqShift.cpp
- src/SurgeRotary.cpp
The FX clever std::map global blew up on windows since dll
initialization order is random. Fix that with an explicit
call that constructs the data structure I wanted anyway.
Closes #151
> Restore windows operations

- azure-pipelines.yml
- plugin.json
- scripts/resetversion.sh
The azure pipeline builds kept the VERSION of the built asset
at 1.0.0. This makes it so the version is 1.alpha.githash.
> Azure Pipeline uses VERSION properly

- README.md
- src/Surge.cpp
- src/SurgeModuleCommon.hpp
- src/SurgeWTOSC.cpp
- src/SurgeWTOSC.hpp
1. Finish the WT UI by adding information on the wavetable to
the screen in that big blank space
2. Clean up some of the log messages we didn't need
3. Make the "getVersion" in SurgeModuleCommon the more accurate
"getBuildInfo" and adjust
Closes #31
> Finish WT; Clean up Logs

- src/SurgeFX.hpp
For a while I thought we needed extended range for delay. We don't
but those old params were still in there. Fix this up before we get
lots of users since it changes streaming format.
> Remove the unused EXTEND params

- patches/RotaryExample.vcv
- src/Surge.hpp
- src/SurgeADSR.hpp
- src/SurgeClock.hpp
- src/SurgeFX.hpp
- src/SurgeLFO.hpp
- src/SurgeOSC.hpp
- src/SurgeVCF.hpp
- src/SurgeWTOSC.hpp
- src/SurgeWaveShaper.hpp
Surge runs on +/- 1.0 for all of its oscillators and stuff
Rack runs on 10v pp which means oscillators run at +/- 5V
I had sloppily made oscillators and effects assume +/- 10v
This change fixes it by introducing proper constants so the
code is clearer at the conversion points, and testing levels
vs Fundamental/VCO in the scope.
Closes #172
> Support voltage levels correctly

- src/SurgeFX.hpp
- src/SurgeModuleCommon.hpp
TempoSync display used the undefined snprintf(a,n,"...", a); whic
on macOS had undefined behavior of working and on linux had undefined
behavior of not working. This meant temposync times didn't display
properly on linux. Fix.
Closes #175
> Fix temposync display

- src/SurgeADSR.hpp
- src/SurgeFX.hpp
- src/SurgeLFO.hpp
- src/SurgeModuleCommon.cpp
- src/SurgeModuleCommon.hpp
- src/SurgeOSC.hpp
- src/SurgeVCF.hpp
- src/SurgeWTOSC.hpp
- src/SurgeWaveShaper.hpp
This commit sets out a path to using a more consistent parmeter
binding class, and in the LFO where that conversion is complete
showing how that gives you the Rack UI features like smarter
right mouse editors and labels.
This addressed parts of #99, #100 and #147. I think I'm going to
collapse those all into #147 and use that to hang the rest of the
implementation of this in the other classes.
> Path to cleaner parameters

- scripts/buildutil.sh
- src/SurgeADSR.cpp
- src/SurgeADSR.hpp
- src/SurgeLFO.hpp
- src/SurgeModuleCommon.cpp
- src/SurgeModuleCommon.hpp
Expand the ParamBinding mechanism to handle a broader group
of types. Apply it to ADSR reducing the ADSR code by a lot.
Turn on custom parambinding aware editors for the ADSR controls.
> ParamBindings for ADSR

- src/SurgeEQ.cpp
- src/SurgeFX.cpp
- src/SurgeFX.hpp
- src/SurgeFreqShift.cpp
- src/SurgeModuleCommon.cpp
- src/SurgeModuleCommon.hpp
- src/SurgeRotary.cpp
- src/SurgeVOC.cpp
Move FX to the ParamBinding class, eliminating a load of
redundant code. Also gives us the right mouse behavior on
all FX widgets properly. Moreover, the temposync widgets
get their name correctly.
Many but not all parameter types are bidirectionally supported
from string. Keep plugging away. But this is good enough to merge
and a real improvement.
> Move FX to ParamBinding

- plugin.json
- src/SurgeADSR.hpp
- src/SurgeClock.hpp
- src/SurgeFX.hpp
- src/SurgeLFO.hpp
- src/SurgeModuleCommon.hpp
- src/SurgeOSC.hpp
- src/SurgeVCF.hpp
- src/SurgeWTOSC.hpp
This change implements a polyphonic oscillator (surge-osc)
allowing all the non-wavetable oscillator shapes to be played
in up to 16 voices. It also removes the dangers-for-poly-port
API points "getInput" and "setOutput" which were vestigal
leftovers from when I wanted to try and have 0.6.2 and 1.0
work at the same time.
> SurgeOSC is polyphonic

- src/SurgeADSR.hpp
- src/SurgeModuleCommon.hpp
- src/SurgeOSC.hpp
- src/SurgeWTOSC.hpp
1. Stupidly the ParamBinding kept forceRefresh true always so toggle it
once refreshed
2. Add some simd helpers to ADSR
3. Fix a CPU stealing bug in OSC and WTOSC where they iterated over way
more parameters than needed to do updates.
> Performance Profiling #1

- src/SurgeModuleCommon.cpp
Used to be I correctly put surge-data in dist but that all changed
sometime, but I sitll had a stale directory so i didn't know it.
User @SteveRussell33 found the error. This is the obvious fix
which is "dist has build in the name so put build in the name".
Closes #203.
> SurgeModuleCommon data location

- src/SurgeModuleCommon.cpp
Rack v1 before 95ea82c2 put distributables of form "build/foo"
into the dist as "foo"; and after as "build/foo". Since I want
this software to run with various v1.0 in the dev period, handle
either outcome when I read the files at the cost of a throwawy
fopen per module creation.
Closes #203
> Data path for different rack versions

- Makefile
- plugin.json
- scripts/make-fx-presets.py
- scripts/resetversion.sh
Versions now take the form of 1.beta1.LOCALBUILD in your dev
area and 1.beta1.(githash) in the CI pipeline from master.
I will branch this to make 1.beta1.0 for the community build.
> Move version to beta1 rather than alpha

- src/SurgePatchPlayer.hpp
PatchPlayer was using default storage data path. For
people with the VST installed this means it worked; for people
without the VST installed this meant it SEGVed. Fix by passing
the plugin path through the constructors.
Addresses #216
> PatchPlayer needs a storage data path

- src/SurgeEQ.cpp
SurgeEQ3 had the input mapped to the param ID for the FX controls rather
than the input ID. That led to a variety of problems, including
not being able to duplicate the EQ3 reliably and having a variety
of crashes and assertion failures.
Closes #231
Closes #232
Closes #233
Closes #234
Closes #237
> Fix input mapping in SurgeEQ3

- src/SurgeFX.hpp
Prior to this diff, I set up the params for FX backwards; I set
their default to zero then set their value with get_f01. This meant
that RMB/Initialize went back to a different state than drag-out-new
So fix this by initializing surge before rack; and then once that's
done read the f01 as the param defaults.
Closes #230
> FX initial state is in config params

- Makefile
When compiling windows software on ubuntu (which rack does for its
builds) case matters; thanks to @cschol for this diff.
Closes #244
> Fix Cross-Compilation Case Error

- src/SurgeFX.hpp
- src/SurgeModuleCommon.hpp
The 'return-value' param was never initialized in surge. This is
actually correct, but I have to handle it in rack, where I care a bit
more. This led to a UMR and a crash
Closes #246
> Fix an uninit memory in the FX

- src/SurgeModuleCommon.hpp
- src/SurgeStyle.hpp
The CLK CV were driving BPM; so relabel them appropriately and
clamp the resulting BPM into a range of (1,1024) to avoid temposync
algos (like rotary) going unstable.
Closes #249
> Clamp BPM to avoid overflows

- src/SurgeADSR.cpp
- src/SurgeBiquad.cpp
- src/SurgeChorus.cpp
- src/SurgeClock.cpp
- src/SurgeEQ.cpp
- src/SurgeFX.cpp
- src/SurgeFreqShift.cpp
- src/SurgeLFO.cpp
- src/SurgeNoise.cpp
- src/SurgeOSC.cpp
- src/SurgePatchPlayer.cpp
- src/SurgeRotary.cpp
- src/SurgeStyle.cpp
- src/SurgeStyle.hpp
- src/SurgeVOC.cpp
- src/SurgeWTOSC.cpp
- src/SurgeWaveShaper.cpp
- src/SurgeWidgets.cpp
- src/SurgeWidgets.hpp
As part of #251 first step is to have SurgeStyle color
names be logical (panelBackgroundOutline) vs physical (darkGray).
This makes that change and a few other color parameterizations.
> Rename SurgeStyle so that the names are logical

- src/SurgeFX.hpp
- src/SurgeOSC.hpp
- src/SurgeWTOSC.hpp
With 1.6.3 oscstorage becomes a class so I need to be a bit
more careful with setupStorageRanges for everything to work
Closes #254
> Handle OSC break with 1.6.3

- src/SurgeBiquad.hpp
The BiQuad filter in some cases could go unstable and NaN out
as reported in #250. This puts the VCV-Rack voltage guidelines
suggested check in place.
Closes #250
> NAN check in BiQuad

- src/Surge.cpp
- src/SurgeModuleCommon.hpp
- src/SurgeRackGUI.cpp
- src/SurgeStyle.cpp
- src/SurgeStyle.hpp
- src/SurgeWidgets.cpp
- src/SurgeWidgets.hpp
- src/UserInteractionsRack.cpp
the rack macro INFO went from "logger::log" to "rack::logger::log"
which is a breaking change if you aren't using namespace rack, which
I'm not. And there's no release planned for that change but the source
buidls have it and the SDKs don't. So this fix works through that again
since I keep breaking my code.
Closes #273
> Further cleanup to Rack API shift

- src/SurgeBiquad.hpp
The frequency upper bound used to drive the filter into NaN
state occasionaly which I fixed with an is_infinite in 1.beta1.2
but that didn't stop the filter from blowing up. This change sets
a bound on the filter frequency in both the knob and knob + CV
dimensions to make sure we don't go outside the stable range.
Closes #275
> Clamp filter frequency bounds

- src/SurgeStyle.cpp
A state in loadStyle forced an empty load, reportedly occasionally
crashing windows.
Addresses #281
> Fix a state where loadStyle would mis-load the style

- src/SurgeModuleCommon.hpp
onSampleRateChange assumed storage was setup. For all modules except
clock and noise it was. This meant that loading clock and noise and
swapping sample rate was a hard crash on mac and a wierd crash on
windows. Addresses #281.
> Handle null storage with sample rate change

- src/SurgeClock.hpp
- src/SurgeFX.hpp
- src/SurgeModuleCommon.hpp
- src/SurgeOSC.hpp
- src/SurgeWTOSC.hpp
There were a couple of impoertant ways in which the SurgeRack
modules were not correct under samplerate changes, and this
fixes them. Addresses #284
> SampleRate Change Handling

- src/SurgeADSR.hpp
- src/SurgeLFO.hpp
the LFO deactivated the wrong way so was always not oscillating
> Fix DeActivation LFO problem

- Makefile
- src/SurgeBiquad.hpp
Make sure we use $(CMAKE) properly
Don't change $CC_FLAGS before a build
And squash an irrelevant warning in the b iqyad
> Remove the blanking of CFLAGS in our makefile

- src/VCO.cpp
- src/VCOConfig.hpp
- src/XTModule.hpp
- src/XTWidgets.h
- Filters Active on Window
- Rescan and Open in wavetable menu (and coming-soon load)
- Don't scan all the WTs if you dont need them
- Menu Component gets a menu glyph and a menu for params
- String is compensated stiffness by default
- SnH Filters On the Panel
> Some VCO Tweaks

- src/FX.cpp
- src/FX.hpp
- src/FXConfig.hpp
- src/XTModule.hpp
- src/XTModuleWidget.hpp
1. ClockProcessor and temposync support which basically sets up tempo and temposync properly
2. Start of showing that wokring in FX but it doesn't work in the presence of modulation alas since I think the set-value-f10 does the temposync bind. But look at that later this week.
> Temposync Started for FX; Freq Shift and Delay panels roughed

- plugin.json
- src/FXConfig.hpp
- src/VCF.hpp
- src/fxconfig/Combulator.h
- src/fxconfig/Distortion.h
- src/fxconfig/Ensemble.h
- src/fxconfig/Neuron.h
- Combulator, Neuron done
- Ensemble has a faceplate but not super happy with it
- Frequency parameter on VCF is now named (duh)
- Brand changes to "Surge XT" and lose the "SXT" from all the modules
> More FX come online; Fix redundant brand and module names

- src/FX.cpp
- src/FX.hpp
- src/VCF.hpp
- src/VCO.hpp
- src/Waveshaper.hpp
1. A crash avoidance in the VCO where we had init and init types out of order in the ctor
2. Labels on all the knobs in the VCF/WS. Addresses #439
3. Start on FX Poly support but leave the menu off. Addresses #451
> A crash avoidance; some labels; start of poly FX

- src/DelayLineByFreq.cpp
- src/FX.hpp
- src/LFO.cpp
- src/LFO.hpp
- src/VCF.hpp
- src/XTStyle.cpp
- src/fxconfig/Ensemble.h
1. Fix an error where LFO thought it had 5 mod inputs which led to an OOB on WIN/LIN which crashed module browser. Closes #457
2. Fix some memory/pointer bounds warnings from gcc which were spot on.
> Fix a Lin/Win error; fix Lin warnings

- src/VCO.cpp
- src/VCO.hpp
- src/XTModule.hpp
- src/vcoconfig/FM3.h
- FM3 moves absolute to module menu, not a light, but also:
- VCOs can add custom items to the module menu from config
Addresses #440
> FM3 moves Absolute to Module Menu

- src/FX.hpp
- src/VCO.hpp
My theory for the clasic crash in #462 is that our params are good but our scenedata isn't when we init. Note that the line which is crashing (230 in classic) refers to the localcopy on the get extended and that won't be initialized without this, so I think it is really it.
> Setup scene/global data in init stage

- src/LFO.cpp
- src/LFO.h
- src/LayoutEngine.h
- src/VCO.cpp
- src/XTWidgets.h
- Dynamic labels on the LFO. #446
- Modulation slider overlays paint more accurately. #446
- VCO and FX Gutter Controls do Undo. #479
- LFO Shape Undo. #479
> Some prep for beta small fixes

- src/Delay.h
- src/DelayLineByFreq.h
- Delays label inputs and outputs
- Mono-delay has PolySum on input
- Both delays implement bypass
Addresses #511
> Delay Line Bypass and PolySum (for mono delay)

- src/VCO.cpp
- src/XTModule.h
Modulation Display was mis-normalized so only percentages gave accurate tooltips or from strings. Correct. Closes #516
Also we used the wrong storage to set checkmarks on the VCO panel. Fixed too.
> Fix modulation display; menu checkmark

- src/LFO.h
The LFO would randomize the entire range of the LFO type but that would run us into formula and mseg which would crash drawing the curve and so on, so properly cap the upper bound on the param to allow randomization to work
Closes #526
> Stop Crash under Randomization of LFO

- src/Delay.h
- src/VCF.cpp
- src/XTWidgets.h
1. Delay time gets 3 decimals. Closes #533
2. LFO subtype gets the right height so the right arrows.
3. A const & to avoid a copy in XTWidgets
> Three super minor tweaks

- src/VCO.cpp
- src/VCO.h
When mis-installed so the wavetables aren't there, the oscillators should still not segv. Now they don't
(but they don't work of course)
Closes #535
> Avoid a crash when mis-installed

- src/VCF.cpp
- src/Waveshaper.h
- src/XTModule.h
- src/XTModuleWidget.cpp
- src/XTStyle.cpp
- src/XTStyle.h
- src/XTWidgets.h
- src/fxconfig/Chorus.h
- src/fxconfig/Chow.h
- src/fxconfig/Combulator.h
- src/fxconfig/Distortion.h
- src/fxconfig/FrequencyShifter.h
- src/fxconfig/Phaser.h
- src/fxconfig/Resonator.h
- src/fxconfig/Reverb1.h
- src/fxconfig/RingModulator.h
- src/fxconfig/SpringReverb.h
- src/fxconfig/TreeMonster.h
- src/vcoconfig/SHNoise.h
- src/vcoconfig/Sine.h
- src/vcoconfig/Twist.h
- src/vcoconfig/Window.h
- Negative-direction wrap on VCF subtype jog works. Closes #546
- Add a WHITE color LED. Closes #547
Then:
- Activate tooltips on the power button and glow non-mod button.
- Make sure all tooltip labels for enable etc... are consistent
- Add correct labels to several modules missing them
- Add an On/Off Param Quantity type which displays On/Off rather than 1/0 and handles appropriate type in.
Above set closes #543
> Friday Fixes from Github Issues

- src/XTModule.h
- src/XTModuleWidget.cpp
- src/XTStyle.cpp
- src/XTStyle.h
- src/XTWidgets.h
1. Four colors (display area, knob rings, power buttons, modulations)
2. All separately addressible, but also knob rings can attach to display by default
3. White rings on light background have darker ring
Closes #551
Closes #554
> Separate the colors a bit more

- src/LFO.cpp
- src/VCO.cpp
- src/XTModule.h
- src/XTStyle.cpp
- src/XTWidgets.h
- LFO click-to-set on the slider. Addresses #559
- Correctly deal with WHITE knob ring in LIGHT skin, after I finally understood what steve meant!
- No osfilter on mac; case multiple for win/lin. Addresses #552
- Add a bloom to small LEDs. Closes #548
- Put a streaming version of 1 in, just for the future
> Saturday fun and tweaks

- src/VCO.cpp
- src/VCO.h
- src/XTWidgets.h
- src/vcoconfig/Twist.h
- Click unison etc.. and get a menu. Closes #568
- Output attenuator in menu. Closes #569
- Fix a problem where twist wouldn't recover from turning the LPG back off.
- Twist turns on LPG automatically when you connect a trigger input. Closes #571
> A few of the initial comments from Lars

- src/VCO.h
- src/XTWidgets.h
- DC Blocker on by default Closes #570
- Restore double click to the UNI etc... controls at the cost of a tiny latency on the RMB menu. Closes #568
> Some sunday morning tweaks

- src/XTModule.h
If your module has polyphony N and your modulator M and M != N we used to always use channel 1. This made sense when M == 1 but had the counter-intuitive behavior of making poly signals implicitly mono silently.
So now in the case of M != N and M != 1, we instead use as much of M as we can and pad the rest with 0. So to be clear if you ahve a polyphony 5 module and polyphony 3 modulator, the modulation amounts will be (ch1, ch2, ch3, 0, 0) whereas before this change they were (ch1, ch1, ch1, ch1, ch1), but that's really unintuitive it turns out.
> Change modulation polyphony when mismatched

- .github/workflows/build-plugin.yml
See discussion [automated-building-and-releasing-plugins-on-github-with-github-actions](https://community.vcvrack.com/t/automated-building-and-releasing-plugins-on-github-with-github-actions/11364/39?u=qno).
I also removed restrictions to run workflow only on origin repository, because it make no sense to me (except Releases and Nightly workflows).
> Update workflow actions

- src/FX.h
- src/LFO.h
- src/VCO.cpp
- src/VCO.h
- src/XTModule.h
- src/XTModuleWidget.h
- src/XTWidgets.h
- Snap Names on Construct. Closes #595
- Label OneShots in the display and change RESET to TRIG in one shot mode. Closes #584
- ThereAreFourLights widget fixes the RMB menu for parameters to be more discrete, in a bit of a wonky way. Closes #589
> More Fixes to User Feedback

- src/Mixer.h
- src/VCF.h
- src/Waveshaper.h
- src/XTModule.h
1. Displayed scale of db was wrong
2. Linear scale of knobs mis-matched surge internals
so
1. Change the db display to be correct; Now setting gain to -4 on a signal does the exact same thing as mixmaster
2. Change the db scaling to be cubic, like the surge mixer does, giving a bigger upside range (to 18db) and finer control on the downside, especially when modulating.
> Fix Decibel Gains in Mixer, VCF and Waveshaper

- src/LFO.h
Fix the case when loading an LFO attached to a gate which hasn't fired at restore-from-patch/construcg
> LFO Startup State Fix

- src/LFO.cpp
- src/XTModule.h
1. Temposync display used a mis-rounded value so the tooltip didnt always match the behavior. Fix and closes #619
2. Actually *set* the polyphony manual mode in the menu so it works. Duh. Closes #618
> TempoSync Display and LFO Manual Poly Fixes

- src/XTWidgets.h
We remove the RoundKnob::shadow member in KnobN. But Widget::removeChild doesn't delete the widget rather it transfers ownership to the caller, so make sure to delete in my constructor.
Don't delelte when we remove incase a base class decides to touch it for some reason.
> Fix a leak of knob shadow

- src/LFO.cpp
- src/LFO.h
- src/VCO.cpp
When deformed, the envelope can be discontinuous if not smapped from zero. Add an optional smoothing function to compensate.
Closes #607
> Add an adjustable one-pole to envelope mode

- src/Delay.h
- src/DelayLineByFreq.h
- src/FX.h
- src/Mixer.h
- src/VCF.h
- src/VCO.h
- src/Waveshaper.h
On discord, Oct 17, Vortico told me:
DSP threads run with
_MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
_MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
_MM_SET_ROUNDING_MODE(_MM_ROUND_NEAREST);
regardless of standalone or plugin.
and the FPU guard here seems to take a lot of CPU in high thread rosetta situations. So don't do it and rely on the rac environment.
> FPU Guard isn't needed

- docs/changelog.md
- src/EGxVCA.cpp
- src/EGxVCA.h
- src/XTStyle.cpp
- src/XTWidgets.h
1. add a 'alpha' label which youc an slap on new modules since folks are using 2.1 while we wait for the library
2. add the alpha label to EGxVCA
3. Fix an fclose-on-nullptr case which may be crashing arch
> Alpha label; FClose fix

- .github/workflows/build-plugin.yml
- scripts/drun.sh
- src/FX.cpp
- src/VCO.cpp
SDK 2.2 has a header order fragility problem. This works around it allowintg 2.2.0 docker builds to work on linux.
> Workaround SDK 2.2 Docker Bug

- src/VCO.h
- src/XTModule.h
This reverts commit 5bb87cc34e820a8e9cfac14662eaf3a2593e5bc1.
It works around the problem reported in #661 but reintroduces the bug in #636
> Revert "Use unmodulated value for modulation tooltip"

- Makefile
- docs/install_steps.md
- src/EGxVCA.cpp
1. Bring in the surge diff which turns off airwindows builds optionally and do that in our dep stage to make CI faster. Closes #652
2. Add a small doc on how to prep an install so I don't have to remember those steps next time. Closes #660
> Turn off AirWindows unused build; add Install docs

- src/Delay.cpp
- src/Delay.h
- src/EGxVCA.cpp
- src/EGxVCA.h
- src/FX.cpp
- src/FX.h
- src/LFO.cpp
- src/LFO.h
- src/XTModule.h
- src/XTModuleWidget.h
Clock caluclation was all in one place, but the json streaming and menu handling was copied and pasted. With a few more moudlator type clock consuming things in the 2.1 milestone, clean this up before we copy it more.
Closes #665
> Centralize some more clock stuff

- src/XTWidgets.h
Modulation arm buttons don't consume press properly. This generally doesn't matter but it means in lock widget mode presisng that button will cause the background to be hit which is a select gesture, improperly.
Closes #676
> The modulatino button doesn't consume press

- src/Waveshaper.cpp
- src/Waveshaper.h
- src/XTModule.h
1. Add a parallel SIMD DC Blocker
2. Use it on the waveshaper
3. Have it on by default for new modules
4. Have it off for 2.0.3.0 streamed sessions
Closes #658
> A DC Blocker for the Waveshaper

- src/LFO.h
- src/XTModule.h
- Step Endpoints non randomizable and a few others too
- The shape is randomizable b ut if you are on step sequencer mode you stay there. Only randomize between the waveforms
Closes #684
> LFO Randomization Improvements

- src/VCO.cpp
Make VCO work with Cardinal, which does not use osdialog due to its event-locking behaviour.
Using a compiler macro so regular VCV Rack builds remain the same.
> Make VCO compatible with Cardinal

- Makefile
1. Pull surge to head as a submodule, pulling in all the changes from the weekend
2. Turn off MTS in the Makefile as well as the dep module. Closes #692
> Pull Surge to head; turn off MTS in rack build

- src/XTModuleWidget.cpp
- src/XTStyle.cpp
Sorry I completely forgot about this small set of changes.
for the wavetable path stuff, we force the plugin to have a valid path in Cardinal, otherwise it ends up pointing to build code dir (which even if module does not load files, is still ugly and incorrect).
not sure if this works fine in VCV Rack, but this approach is preferred in Cardinal so that `dataPath` always points somewhere valid.
for the theme stuff, I hide the menu options and let Cardinal handle the theme changes.
this is because Cardinal provides its own `bool rack::settings::darkMode` API for it, which I add support in as many modules as possible.
the result is a single option on the "view" menu that switches all possible modules from dark mode to light mode and vice-versa. surge integrates into this well too.
there is …
> Final Cardinal related changes

- CMakeLists.txt
- src/QuadLFO.h
- src/XTWidgets.h
- src/dsp/SimpleLFO.h
1. Return -Werror on Darwin
2. Add a DEBUG flag so I can panel-show debug builds
3. Fix a bug in FREEZE mode with non-constant jumps
4. Make Quad LFO scales by x/ rather than decimal
> Quad LFO and CMake tweaks

- src/XTModule.h
MOdDepth typein was incorreclty scaled. Correct.
Closes #698
> Fix Surge ModDepth Typein Problem

- src/Delay.h
- src/XTModule.h
this means Delay Clock only works in BPM mode; correct and resulting delay clock now works.
Closes #740
> Delay Clock didn't get SampleRate

- src/EGxVCA.cpp
- src/EGxVCA.h
- src/XTModule.h
1. Have a type switchable param quantity by mode more easily ready
2. Use it to at least morph out the DAHD vs ADSR params in EGxVCA
> Improve Switchable Params; Apply to EGxVCA

- RackSDK.cmake
1. quick_install uses TARGET_FILE to get all the suffxes
2. Update surge so it compiles if you force AVX2against our will
> Two small fixes for builds (AVX; quick install)

- src/VCO.cpp
- src/VCO.h
Double downloads conflict horribly. Move the is-download indicator from module-local to process-static, deactivate the menu when downlaods are ongoing, don't laucnh a new one if an old one is on, etc..
Closes #747
> Don't allow double downloads

- CMakeLists.txt
- Makefile
- README.md
- RackSDK.cmake
This is my proposal to build the plugin dist just with CMake and not rebuild it again with Make build.
It basically works, but I'm not sure if this approach is OK.
The only weird thing is that at first call Make creates a "empty plugin" (enforced by `all` target), but it gets immediately overwritten with the cmake built plugin (copied from cmake build), so it doesn't matter.
The trick is to copy the CMake built plugin into the project dir so the dist target is using it and Make doesn't need to build the plugin completely again.
With this it is possible to get rid of all the extra build instructions in the Makefile and have now a generic working Makefile that can just be thrown in a CMake based Rack plugin project for building a proper release. The only thing required to set is the …
> Use cmake built plugin

- src/QuadLFO.h
- src/VCO.cpp
- src/VCO.h
Modulation tooltip was based on oscstorage_display which was modulated to animate the display so it was totally wacky. Change it so the display has the base values and modify through the tp[] structure etc... so the animation continues but the tooltips reflect base properly. Closes #636
Also set defaults for rate on QuadLFO propelry and fix a typo there in a dropdown
> Updare VCO Modulation Tooltip Display

- src/XTModuleWidget.cpp
- src/XTWidgets.h
This is a kinda ugly one, but needed in order to build with LTO on mingw.
I can't really explain it, unpatched code is valid, so this just seems to be a compiler bug.
build error log example:
```
Creating LV2 plugin for Cardinal
/usr/bin/i686-w64-mingw32-ld: VCO.cpp.o (symbol from plugin):(.gnu.linkonce.t._ZN3sst12surgext_rack7widgets23VerticalSliderModulatorD1Ev[__ZThn80_N3sst12surgext_rack7widgets23VerticalSliderModulatorD1Ev]+0x0): multiple definition of `sst::surgext_rack::widgets::VerticalSliderModulator::~VerticalSliderModulator()'; Delay.cpp.o (symbol from plugin):(.gnu.linkonce.t._ZN3sst12surgext_rack7widgets23VerticalSliderModulatorD1Ev[__ZThn92_N3sst12surgext_rack7widgets23VerticalSliderModulatorD1Ev]+0x0): first defined here
/usr/bin/i686-w64-mingw32-ld: VCO.cpp.o (symbol from …
```
> Workaround for mingw LTO builds

- src/QuadAD.cpp
smpEvery should be at least 1 otherwise the mod for downsampling blows up in curve draw
> QuadAD draw sampling underflow

- src/FX.h
- src/VCO.cpp
- src/VCO.h
- src/vcoconfig/Alias.h
- The memory locations don't make sense in rack
- Supress them at a UI level and if they hit the engine flip em off there too
Closes #706
> Alias Modes for Memory Locations supressed

- src/VCO.h
- src/vcoconfig/String.h
- src/vcoconfig/Twist.h
If you changed a sample rate in a running session, Twist didn't re-initialize properly.
Closes #767
> Fix a Twist SampleRate Change problem

- src/VCO.h
- src/vcoconfig/Twist.h
It now matches Macrooscillator 2.
> Update Twist Decay to sweep block size bug

- .github/workflows/build-plugin.yml
- .gitignore
- Makefile
- RackSDK.cmake
SDK 2.2.2 changes target name to plugin-arm64 so:
1. Make that switch on ${RACK_PLUGIN_LIB}
2. Since RPL is now no longer a stable name name a RACK_BUILD_TARGET dummy target called 'build_plugin' and modify quick install rule accordingly
3. Update the Makefile for new name
4. Update GHWF for 2.2.2 for mac
> Update Mac build for 2.2.2

- src/FX.cpp
- src/FX.h
1. The FX revert optimization I used for #707 falsely passed my test here because I also have Surge installed, so revert that (at the cost of FX startup scanning wavetables again) and reopen #707
2. Even in that case, the jog selector shouldn't crash, but it was non-defensive for empty presets. Fix that by guarding a bit more. Closes #772
> Revert FX Load Optimization; Fix 0 Presets Crashes

- src/VCO.h
- src/vcoconfig/Twist.h
Now I have the LPG triggering properly we need to not reconstruct continuous voices when retriggered with the LPG on but do need to retrigger in alternate cases, so hand retriggerability to a specialized VCOConfig and implement it conditionally for Twist; and set the gate on the oscillator accordingly.
Closes #773
> Change LPG Twist Init Cycle

- src/FX.h
- src/fxconfig/Exciter.h
The exciter effect is very succepitlbe to levels and in a chain would NaN out. Fix this with two things
1. Scale the inputs and outputs to make the signal we send a bit less 'hot'. This is similar to the attenuatino of the half band filter in the VST which the effect is callibrated for
2. Softclip the outputs in case it does get spiky so we don't send overflow down the pipe
3. Add these as config options which are constexpr off for everyone else
Closes #749
> Exciter NaN / Overload avoifdance

- .github/workflows/build-plugin.yml
- Makefile
- RackSDK.cmake
- src/FX.cpp
- src/VCO.cpp
Synced with my `RackSDK.cmake` changes from https://github.com/qno/vcv-plugin-cmake-example.
Built with updated toolchain docker image with Rack SDK 2.2.2.
> Update to Rack SDK 2.2.2

- src/ModMatrix.cpp
The width didn't take negativity into account.
Closes #802
> ModMatrix display for -ve values wrong

- src/EGxVCA.cpp
- src/EGxVCA.h
1. Attack not Attach. Closes #815
2. Render at least a quarter second envelope even if A D R are zero. Closes #816
> Two EGxVCA tweaks

- src/FX.h
- src/LFO.h
- src/Mixer.h
- src/QuadAD.h
- src/QuadLFO.h
- src/VCO.h
- src/Waveshaper.h
- src/XTModule.h
Closes #817. Tested by running valgrind linux and stressing it on macOS.
> Move to json_object_set_new consistently

- docs/changelog.md
- src/VCO.h
As described in #814 double loaded from 203 and extra would double up menus. Fix that
Also update the changelog ready for 2.1.1
Closes #814
> Don't double-show 2.0.3 and extra wavetables

- docs/changelog.md
- src/EGxVCA.cpp
- src/EGxVCA.h
- src/XTModule.h
- src/dsp/ADSRDAHDEnvelope.h
When D in DAHD is at minium, follow the ADSR legato mode and skip the vanishingly small delay step unconditionally (although retrig from zero still will, as will any delay above the min).
Closes #812
> DAHD Retrigger

- src/XTModule.h
There is a typo inside the assert, leading to a build error if DEBUG is set (which enables assertions)
I suggest to add a debug build to CI to catch these.
> Fix debug build (typo in assert)

- src/EGxVCA.h
1. The VCA gate for a mono gate poly input broadcasts the gate to the other channels. Addresses #838
2. Add a stage which does a direct debug build. Closes #837
> Monophonic VCA Gate; A debug-testing CI stage

- docs/changelog.md
- src/VCO.cpp
Fixes this problem by using the modulated value for the z position in the recalc path 3d calculation. Basically a bug when porting from juce.
Closes #841
> Modulated 3D Wavetable Curve didn't Z-Shift

- src/Mixer.h
The 'unmute on connect' handy utility conflicted with unstreaming the mute status. So if you unstream json then set the 'ever connected' to true which is best you can do. Closes #852
> Turn of unmute-on-connect mixer on json unstream

- CMakeLists.txt
- src/DelayLineByFreq.h
- src/DelayLineByFreqExpanded.h
- src/Mixer.h
The Mixer and TunedDelay didn't follow the protocol that left-only was a stereo signal broadcast to both channels. Correct.
Closes #860
> LeftRight Normalization on Mixer; TunedDelays

- src/vcoconfig/Twist.h
The LPG hides basically all the useful features of the waves when painted for a few cycles so just don't use it on the display oscillator
Closes #846
> Don't paint the LPG response on the Twist scope

- src/LFO.cpp
- src/LFO.h
1. Always show the LFO wav just lightly, just like in surge
2. Deform is Bipolar! Make the knob bipolar also
CLoses #847
> LFO Display Fixes; Under Wav and Bipolar Deform

- docs/changelog.md
- src/VCO.cpp
1. Fill frames for truncated tables with 0, fixing a problem with pulse wavetable in rack. Closes #843
2. Invalidate more completely when dirty since background is dirty dependent. Addresses #856 but will await for confirm to close
> Wavetable Painting and Loading Fixes

- src/XTWidgets.h
ParamStepped used to be not a param widget but now it is; but we still had the apocryphal shadows of module and paramid. This was fine-ish except when you asked for widget->getParamQuantity in a context where you didn't check for NULL. Stormelder strip is such a context so this would crash when strip randomized.
Closes #876
> Un-shadow Module and ParamID in ParamStepped

- src/Delay.h
- src/DelayLineByFreqExpanded.h
- src/VCO.h
Rack adds "input" to input tooltips so an input named "Audio Input" shows a tooltip of "Audio Input Input". Fix.
Closes #878
> InputInput

- src/Waveshaper.cpp
- src/Waveshaper.h
- src/XTStyle.cpp
- src/XTStyle.h
Make the waveshaper display system wide style level setting. Default it to the old display (single curve).
Closes #883
> Make the WaveShaper display system-wide

- src/Mixer.h
The Mixer Tooltips for mute/solo etc... and the named labels for the levels were all just wrong. I don't know how this slipped by for so long!
Anyway: fixed. Closes #900
> Correct Mixer Tooltips

- CMakeLists.txt
if RACK_DIR was ../foo then the SIMDE path got the wrong relative directory and code wouldn't build. Flash it to absolute using cmake intrinsics
> Fix a simde path fragility

- src/XTModule.h
A better solution would be nice one day but at least now they show up in the log.
> Route Surge Errors to the Rack log as WARN

- src/XTWidgets.h
1. R1 Size is modulatable now we have updated surge to head and fixed it. Closes #871
2. Replace the deprecated getSmoothValue -> getValue. Closes #870
> R1 Size Modulatable; getSmoothValue -> getValue

- plugin.json
- src/SurgeXT.cpp
- src/SurgeXT.h
- src/UnisonHelper.cpp
- src/UnisonHelper.h
- src/XTWidgets.h
The unison CV expander allows you to route poly or mono CV alongside the unison layout to modulate your target VCO
Closes #928
> Unison CV Expander

- src/UnisonHelper.h
If you use the unison module and *don't* hook up the right output, we skip the unison stereo pan and just sum the voices onto L.
> Unison: Mono mode no longer stereo pans

- docs/nightlychangelog.md
- src/XTWidgets.h
If a param is a ct_freq_blah with rang > 120, add a v/oct auto modulation menu item to the RMB.
Closes #610
> Add v/oct modulation for frequency surge params

- docs/nightlychangelog.md
- src/EGxVCA.h
EGxVCA didn't reset schmidt triggers when channels changed. This meant in some startup cases, with a poly signal and a mono gate, the first gate fired at startup would not trigger the envelopes (but the second and subsequent worked fine).
Fix this in the general case of poly-changes-while-gate-high
Closes #874
> EGxVCA Poly Trigger on Channel Change

- docs/nightlychangelog.md
- src/LFO.h
Rework the innards of LFOxEG to be way less confusing with better named variables etc
As a result, fix a bug which occured when both GATE and GATEENV were connected.
Closes #850
Also bring Surge up to the 1.3 candidate
> LFOxEG GATE/GATEENV fixes

- .gitmodules
With surge 1.3 there's a basic-blocks in there already
> Remove the copy of sst-basic-blocks now surge has it

- src/FX.cpp
- src/FX.h
- src/fxconfig/Nimbus.h
Closes #958
Basically the mode and quality can be excluded from randomization and are by default. Just like twist.
> Nimbus Randomizacion Control

- src/FX.h
- src/fxconfig/Chow.h
- src/fxconfig/Nimbus.h
- src/fxconfig/SpringReverb.h
The NanCheck and Extra Inputs get poly aware
So the spring reverb can be poly knocked
and nimbus can be poly frozen
Closes #961
> Deal with Poly NanCheck and Extra Inputs; Numbus Freeze

- src/FX.h
- src/VCO.h
Anticipating a nimbus change and realizing I stream ints as val01 in the FX so a range change would break patches, with XT2.2 stream (but don't unstream) param integers in the FX also just like we do in SurgeXTEffectsBank
> Defensive param streaming in FX

- docs/nightlychangelog.md
- src/DigitalRingMod.h
- src/VCO.h
The halfrate filter doesn't work at block size 4 currently.
> Up the Digital RingMod oversample latency to 8

- docs/nightlychangelog.md
- src/LFO.cpp
- src/Waveshaper.cpp
> Uni- and Bi-polar LFO waveforms properly align

- src/DigitalRingMod.h
1. The switch went to n_cxm_modes not n_cxm_modes-1
2. The link was randomizable and that's not what you want
Closes #967
> Fix two CXOR range/randomization errors

- src/QuadLFO.h
Quad LFO mis-read the trigger index meaning defacto only the first LFOs trigger would trigger the LFO in independent mode.
Fix this with a 3 char fix to use the right input for the trigger
Closes #970
> Quad LFO Independent Trigger Fix

- src/XTStyle.cpp
Now that VCV Rack has an official dark theme switch we can get a bit closer to the official Rack approach.
The Cardinal custom `rack::settings::darkMode` is being deprecated in favour of the official `rack::settings::preferDarkPanels`
I still do not like having the "mid" as the initial surge theme though, so light/dark switch remains for the initial/first instance of your plugins.
Thanks for the nice modules once again
Next Cardinal release is planned for 15th of January btw.
> Less cardinal specific changes

- CMakeLists.txt
- don't fail 32 bit early
- only use fnochar whatzit if c++ is 20, which it isn't in version 2.2.* / srg 1.3.*
Closes #975
Closes #976
> Allow some non-rack build configurations to proceed

- docs/nightlychangelog.md
- src/LayoutEngine.h
- src/XTWidgets.h
- src/fxconfig/RingModulator.h
Knobs and Menu Items get dynamic deactivation as an option. The ring modulator uses this.
> Dyanmic Deactivation of Widgets; Use in RingMod

- src/Waveshaper.h
Fixes #992
1st change is needed for the case where plugin UI runs while Rack/Cardinal is bypassed which makes this:
```
ddb = module->modulationAssistant.values[Waveshaper::DRIVE][ch];
```
read uninitialized values (they are only set during processing)
2nd change is more obvious, fixes the use of `displayPolyChannel` which does not have a value set.
This also matches what https://cplusplus.com/reference/atomic/atomic/atomic/ says
> (1) default constructor
>    Leaves the [atomic](https://cplusplus.com/atomic) object in an uninitialized state.
which I didn't know it was a thing, I thought `std::atomic` types would initialize to 0...
> Fix uninitalized values in Waveshaper

- CMakeLists.txt
There is still a `-fno-char8_t` in place which breaks builds with GCC7, which can be removed since a few lines above we have:
```
if (CMAKE_CXX_STANDARD GREATER_EQUAL 20)
message(STATUS "Turning on fno-char8_t for c++20")
add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-fno-char8_t>)
endif()
```
> Do not use -fno-char8_t on regular builds

- src/VCF.h
Upgrade surge to 1.3.2
Also set the FPU guard in the VCF to perhaps address #1001
If this doesn't fix #1001 back down that FPU Guard
> Upgrade Surge; FPU Guard VCF

- src/FX.h
I want i%4 + 1, not (i-P0)%4 + 1.
> Fix an error with FX Mod Param Labeleing

- src/EGxVCA.h
Set release curve tooltip to say "Release Curve". Fixes #1018.
> change release curve tooltip to say 'Release' from 'Decay'

- docs/changelog.md
- src/EGxVCA.h
In tepmosyc/clock mode the EOC would not fire on the change on end of cycle, due to a nesting error in the code really.
Closes #1021
> Fix an EOC in temposync ommission in EGxVCA

- .github/workflows/build-plugin.yml
- src/FX.h
params default to deact true and surge patch load, which we run in vst startup, sets them to false, but the phaser was exposed to that not happening, so hard set the fx deact to false and then load and init.
> Deal with deactivated params
